### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1350]
Hi,

I'm seeing `.travis.yml` in the repo, but it looks like tests don't actually run in CI.

Mind enabling repo in Travis?

**Comment by webknjaz** [comment]
Well, you could use brand-new integration, which allows you to restrict Travis access to this repo only if it helps.

**Comment by webknjaz** [comment]
@retr0h would this help?

**Comment by retr0h** [comment]
Not something we are going to do.

**Comment by webknjaz** [comment]
Sad to hear that

**Comment by webknjaz** [comment]
@ssbarnea don't worry, we'll enable it around Oct 29 once it's under @Ansible

**Comment by ssbarnea** [comment]
@webknjaz I hope you will use GitHub transfer for doing this as this keeps all existing tickets and makes a nice redirec from old location to new location.

**Comment by gundalow** [comment]
@ssbarnea yes, I will be doing that, see https://groups.google.com/forum/#!topic/ansible-devel/U8_Lxg7wAHA

**Comment by ssbarnea** [comment]
I am really happy to see these changes comming!

BTW, If one of you can have a look at https://github.com/metacloud/molecule/issues/1521 it would be great.

**Comment by gundalow** [comment]
Setting as v2.20 milestone (next release)

**Comment by webknjaz** [comment]
Fixed by #1541
