### ISSUE TITLE
Allow the "destroy" step to access the vault-password-file variable set in molecule.yml

### ISSUE THREAD

**Issue by mattthehearn** [ansible/molecule#1357]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/mhearn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
molecule, version 2.7.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior
I'm testing a role that joins a new VM to my spacewalk server.  Once the role testing is complete, I need the destroy step to run a shell command on my spacewalk server to remove the test containers from it (so I don't end up with dozens of unneeded systems in spacewalk that I have to clean up later).  I have no problem running the shell and using delegate_to to log into the spacewalk server, but I need to specify a password; I have a vault-encrypted password that molecule already uses to join the container to spacewalk during the converge step, so I'm using the following to point to my vault password file:

```
provisioner:
  name: ansible
  options:
    vault-password-file: ../../test/.vault_pass
```

The destroy step doesn't seem to have access to that configuration setting, though, and I can't for the life of me figure out where to put it in destroy.yml, so I get this:

```
    TASK [Remove added systems from spacewalk server] ******************************
    fatal: [localhost]: FAILED! => {"msg": "Attempting to decrypt but no vault secrets found"}
```

The only workaround I can think of is doing a local step that adds the vault-password-file to the ansible.cfg that molecule creates, but that seems dangerously kludgey, particularly when I get around to running this in my Jenkins environment.

**Comment by retr0h** [comment]
I'll have to figure this one out.  Currently, I strip options from create/destroy since a user can inadvertently cause those built in plays to break.

**Comment by mattthehearn** [comment]
Yeah, I try not to mess with the create and destroy playbooks, this is the first time I've done so. It'd be nice if there was a playbook designed for user customizations as part of the destroy process, similar to the "prepare" playbook when creating the instances.  I suspect that's a pretty significant change, however.

**Comment by retr0h** [comment]
It has been suggested [before](#1304).

**Comment by retr0h** [comment]
Any suggestions on a name for this phase?

I kind of like `pre_destroy`, but that makes prepare seem misnamed.

**Comment by kdask** [comment]
`pre_destroy` sounds reasonable. The good thing about this name is that it's easy to understand the meaning of this phase by just looking at its name. We actually have a separate play named exactly that in `destroy.yml`. We use it to collect various artifacts from molecule instances (applications' logs and other stuff).

A separate phase would be nice. But it's not clear to me how this phase will behave:
- On which hosts will it operate by default? The `destroy` phase operates on `localhost` but it looks like `pre-destroy`, similarly to `prepare`, should operate on `all`.
- Should it always be called before `destroy`?
- What if error occurred during `create`? Should Molecule call `pre-destroy` in this case?

**Comment by epu** [comment]
Does setting this in the ansible config work for you?
`provisioner:
  name: ansible
  config_options:
    defaults:
      vault_identity_list:
        - "{{ molecule_scenario_directory }}/<relative-path-to>/test/.vault_pass"
`

**Comment by mattthehearn** [comment]
@epu, that did it, sort of!  I didn't put it in as a list, but like this:

```
provisioner:
  name: ansible
    config_options:
      defaults:
        vault_identity_list: "../../test/.vault_pass"
```

And it's working great.

**Comment by epu** [comment]
Ah, that's great! I've been struggling with getting this working locally, and you're right - you can't pass a list as vault_identity_list value (neither the yaml list items nor the `[ ]` square bracket syntax work).

Thanks, your answer helped me too - I have 2 identities I've been struggling to use, and using a csv list as the value works ok. That is, `vault_identity_list: "../../test/.vault_pass,../path/to/other/identity/.vault_pass"` works for me.

**Comment by retr0h** [comment]
So, the reason this doesn't work is b/c I strip provisioner options from create/destroy.  However, I am not preventing these options from being set in the `config_options` section.  This was a mistake on my part, b/c one area of Molecule isn't being consistent with the other area.  I'm going to go back and see specifically what was causing issues, b/c your use case is completely valid, and I should probably just blacklist the specific options vs all options.
