### ISSUE TITLE
Molecule shouldn't call external programs directly to avoid shebang limitations

### ISSUE THREAD

**Issue by kdask** [ansible/molecule#1415]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.6.2
```

```
$ molecule --version
molecule, version 2.16.0
```

Molecule installation method:

- pip

Ansible installation method:

- pip

# Desired Behavior

Molecule should work as expected even with virtual envs nested deeply in directory tree.

# Actual Behaviour

The length of shebangs in Linux is limited by `BINPRM_BUF_SIZE` set in `include/linux/binfmts.h`. By default `BINPRM_BUF_SIZE=128`. This value can't be changed without recompiling the kernel.

We currently run molecule with [Tox](https://github.com/tox-dev/tox) and Jenkins and sometimes, when path to some executable (i.e. ansible-playbook) becomes too long, Molecule fails. For example, here is an excerpt from Molecule's log running in our typical environment: 

```
--> Scenario: 'default'
--> Action: 'syntax'
<REDACTED>
DEBUG: COMMAND

/opt/jenkins/workspace/Molecule/test_role/roles/some_longer_than_usual_role_name/.tox/some_longer_than_usual_role_name-current/bin/ansible-playbook --skip-tags=molecule-notest,notest --diff --inventory=/tmp/longer_than_usual_role_name-current/ansible_inventory.yml --syntax-check /opt/jenkins/workspace/Molecule/test_role/roles/some_longer_than_usual_role_name/molecule/default/playbook.yml -vvv

ERROR: 

An error occurred during the test sequence action: 'syntax'. Cleaning up.
```

Executable `/opt/jenkins/workspace/Molecule/test_role/roles/some_longer_than_usual_role_name/.tox/some_longer_than_usual_role_name-current/bin/ansible-playbook` has rather long shebang:
```
#!/opt/jenkins/workspace/Molecule/test_role/roles/some_longer_than_usual_role_name/.tox/some_longer_than_usual_role_name-current/bin/python
```

Its length is 137 which obviously exceeds BINPRM_BUF_SIZE limitation mentioned above.

I see several possible **workarounds** for this problem:

* **Do not use tox and venvs.** This kills one of the most cool things about Molecule: the ability to test roles in different environments against multiple versions of Ansible.
* **Do not use long roles names and/or long tox env names.** We've been trying to do this for a while but it's not always possible and it's incredibly inconvenient.
* **Do not call external executables directly**, instead parse shebang (if said executable has one) and call the interpreter explicitly. Actually Tox took this exact approach some time ago:
    * https://github.com/tox-dev/tox/issues/66
    * https://github.com/tox-dev/tox/blob/46fca4c3c817f0a4728552e99e89ace9b2cc6234/tox/venv.py#L420

I've [tried implementing](https://github.com/metacloud/molecule/compare/master...kdask:shebang-limitations-workaround) this last workaround and it does seem to solve the problem. I don't know how I feel about this implementation though: looks a bit hacky to me, but, well :) Tell me what you think!

**Comment by kdask** [comment]
> Ya, I think the sh module does the finding of the executable on it's own. I don't think it can be tricked this easily.
I think finding the executable isn't a big part of the problem. I agree with you that it's wise to let the `sh` do its work here.

The proposed workaround does some additional juggling after the executable was found:

0. Read shebang from the executable, find out path to the interpreter
1. Move the executable's path to the list of arguments: from `Command._path` to `Command._partial_baked_args`
2. Write path to the interpreter to `Command._path`

So it effectively transforms calls like `/some/executable args` to `/path/to/interpreter /some/executable args`.

Do you think it's possible to add such behavior to Molecule? Maybe even disabled by default like [they did it in tox](https://tox.readthedocs.io/en/latest/config.html#handle-interpreter-directives-with-long-lengths)?

>  I'd hate to suggest not using tox.

Not only tox, but venvs altogether :( For example, Jenkins pipeline paths tend to be rather lengthy on their own. Add venv paths to the mix and you'll run into this issue sooner or later, which can be quite confusing to users since there's no meaningful error message.

**Comment by retr0h** [comment]
PRs welcome.

**Comment by kdask** [comment]
Sure, in a couple of days I'll create PR based on the code from my original message: https://github.com/metacloud/molecule/compare/master...kdask:shebang-limitations-workaround

I'll make this stuff disabled by default.

**Comment by Moep90** [comment]
@Oloremo 
My current Jenkinsfile which works well:
```
$ cat Jenkinsfile
node {
  notifyBitbucket()

  try {
    stage('Sourcecode') {
      cleanWs()
      dir('<rolename>') {
          checkout scm
      }
    }

    stage('Info') {
      sh '<rolename>/ci/scripts/info.sh buildserver'
    }

    stage('Pull Images') {
      withCredentials([usernamePassword(
        credentialsId: '<credsID>',
        usernameVariable: 'REGISTRY_USERNAME',
        passwordVariable: 'REGISTRY_PASSWORD'
      )])
      {
          sh '<rolename>/ci/scripts/images.sh'
      }
    }

    stage ('Create vEnv'){
        if (!fileExists('.env')){
          sh 'ls -lsah'
          sh 'tree'

          sh 'virtualenv --no-site-packages .env'
      }
    }

    /*
      Virtualenv has to source every time
      Jenkins opens a new shell on every "sh" command
   */
    stage ('Prerequisites') {
        sh """
        . .env/bin/activate
        pip install -r <rolename>/ci/scripts/requirements.txt
        <rolename>/ci/scripts/info.sh env
        """
    }

    stage ('Lint'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule lint || molecule --debug lint
          molecule destroy || molecule --debug destroy
          """
      }
    }

    stage ('Syntax'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule dependency || molecule --debug dependency
          molecule syntax || molecule --debug syntax
          """
      }
    }

    stage ('Create') {
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule create || molecule --debug create
          """
      }
    }

    stage ('Prepare Tests'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule prepare || molecule --debug prepare
          """
      }
    }

    stage ('Converge Tests'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule converge || molecule --debug converge
          """
      }
    }

    stage ('Idempotence Tests'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule idempotence || molecule --debug idempotence
          """
      }
    }

    stage ('Side effects Tests'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule side-effect || molecule --debug side-effect
          """
      }
    }

    stage ('Verify Tests'){
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule verify || molecule --debug verify
          """
      }
    }

    stage('Cleanup') {
      ansiColor('xterm') {
          sh """
          . .env/bin/activate
          cd <rolename>
          molecule destroy || molecule --debug destroy

          # Executing from withing ansibe-role dir
          ci/scripts/cleanup.sh
          """
      }
    }

    // Set the result for StashNotifier Plugin
    currentBuild.result = 'SUCCESS'
  } catch(err) {
    // Set the result for StashNotifier Plugin
    currentBuild.result = 'FAILED'
  } finally {
    notifyBitbucket()
    cleanWs()
  }
}

```

And my molecule playbook:
```
cat molecule/default/playbook.yml
---
- name: Converge
  hosts: all
  vars:
    - <costum vars>
  roles:
    - role: <rolename>

```

**Comment by retr0h** [comment]
I'm going to hold off from merging this.  As you know [Ansible is adopting Molecule](https://groups.google.com/forum/#!topic/ansible-project/ehrb6AEptzA), therefore I do not want to merge anything that may impact future architectural decisions, as I will no longer be leading the development of this project.

**Comment by gundalow** [comment]
Hi, there is a proposed fix in https://github.com/ansible/molecule/pull/1461 though we'd welcome your ideas on how we can test this, comments very welcome on the PR

**Comment by ssbarnea** [comment]
I decided that we should avoid adding such a hack into molecule. This should be addressed by the tools producing these broken shebang lines, not molecule.
