### ISSUE TITLE
Cannot use Docker images that do not run as root

### ISSUE THREAD

**Issue by ifireball** [ansible/molecule#1449]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version
ansible 2.6.3
...
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

```
molecule --version
molecule, version 2.17.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

It should be possible to let Molecule know that the base image it is told to use does not run things as root inside and therefore either:
* `sudo` aught to be used to install the extra packages Molecule adds to the derived images it generates

or:

* `USER` directives should be added to the `Dockerfile` molecule generates so that it switches to root to run the extra installation commands it adds and then switches back to the original image user.

**Comment by retr0h** [comment]
The Dockerfile is a template provided to the user to do things as they wish.  If you wish to use USER or add sudo to the commands feel free.  Molecule does not run docker with sudo on my mac.

**Comment by ifireball** [comment]
I meant use sudo from inside the Dockerfile, not run docker with it... also since non-root images aught to be common, I'd rather see a built-in feature to support them rather then having each user of such an image have to tweak the Dockerfile

**Comment by retr0h** [comment]
I don't really have the cycles to implement this.  Since you can update your own Dockerfile to support this, please do so, and if you feel necessary submit a PR so others may benefit from this work.

**Comment by ssbarnea** [comment]
I think is critical to be able to run tasks as both root and non root on docker containers as part of role testing. What happens is very different when you are root.

Now I see that these are running as root, which is ok for 50% of my role testing. Now I need to find a way to test its use as non root. How?

**Comment by gundalow** [comment]
Reopening as at the minimum his is something we need to document (and maybe even write code for).

Does anyone have a work around for this?

**Comment by lwm** [comment]
Does https://github.com/ansible/molecule/pull/1526 solve this?!

**Comment by icollar** [comment]
I came across this issue yesterday and #1526 doesn't solve it for my use case. The workaround I used was to update the Dockerfile.j2 so that it had an optional user switch statement during the build process. In this instance I've an image that cannot, purposely, use DNS. Since Molecule needs to install dependencies I switched the user back to root, enabled DNS, then revert this change after the installation.

```
# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if "instance-1" == item.name %}
USER root
RUN sed -i 's/\(hosts:.*files\)/\1 dns/' /etc/nsswitch.conf
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash || true && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi

{% if "instance-1" in item.name %}
RUN sed -i 's/^\(hosts:\s*\).*/\1files/' /etc/nsswitch.conf
USER runner
{% endif %}
```

**Comment by davidaparicio** [comment]
Some updates about this issue ? 
Or at less, a documentation/example ?
