### ISSUE TITLE
Support Linode as a test driver

### ISSUE THREAD

**Issue by lwm** [ansible/molecule#1450]
# Issue Type

- Feature request

# Feature

Following from https://github.com/metacloud/molecule/issues/1400, we've decided to use Linode as our driver of choice. I am creating this ticket to see if you have similar feelings about adding Linode as a driver of which [we](http://aptivate.org/) are actively using. There is the Ansible module https://docs.ansible.com/ansible/2.6/modules/linode_module.html, so I think should be a fairly simple implementation. I'll get started on that if no one is against adding it.

**Comment by retr0h** [comment]
The only drawback to having a linode driver is the inability for me to test it.  However, if you wish to submit it and follow the existing openstack, gce, aws plays, we can give it a go.

**Comment by lwm** [comment]
OK, cool! I'll be working on getting this submitted. I've seen that the Linode module is in fact, not really in a 'healthy' state (via https://github.com/ansible/ansible/issues/36348) but will hopefully be doing something about that ASAP also.

**Comment by lwm** [comment]
https://github.com/metacloud/molecule/pull/1458 is ready to review now. Thanks.

**Comment by retr0h** [comment]
I'm going to hold off from merging this.  As you know [Ansible is adopting Molecule](https://groups.google.com/forum/#!topic/ansible-project/ehrb6AEptzA), therefore I do not want to merge anything that may impact future architectural decisions, as I will no longer be leading the development of this project.
