### ISSUE TITLE
Delegated driver should respect login_cmd_template

### ISSUE THREAD

**Issue by pieteravonts** [ansible/molecule#1497]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.6.4
  config file = /home/pavon1000248194/it-ops-inventory-sdf/test/ansible.cfg
  configured module search path = [u'/home/pavon1000248194/it-ops-automation/library']
  ansible python module location = /usr/share/venv/ansible-2.6.4/lib/python2.7/site-packages/ansible
  executable location = /usr/share/venv/ansible-2.6.4/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

```
molecule, version 2.18.1
```

Molecule installation method (one of): pip

Ansible installation method (one of): pip

# Desired Behavior

Use a non-ssh connection with the delegated driver.

I want to test my molecule scenario on a kubernetes cluster. If I use the docker driver and my own create.yml and destroy.yml playbooks, it all works except that I cannot use the  login command since it defaults to `docker exec`.
If I use the delegated driver with managed=true, I cannot override the login cmd.
If I use the delegated driver with managed=false, It skips the create and destroy steps.

My problem would be solved if the delegated driver would respect the login_cmd_template in managed mode or if there is an option to enable create and destroy in unmanaged mode.

**Comment by lwm** [comment]
Right, it seems like the delegated driver has a very specific design behind it and what you want is definitely beyond that :) I think your suggestions are sensible but I would have to rely on @retr0h or @wilmardo for guidance. 

I would lean towards keeping the idea of 'managed' meaning create/destroy control and then de-couple the login command overriding. So, basically:

> problem would be solved if the delegated driver would respect the login_cmd_template in managed mode

**Comment by ssbarnea** [comment]
I think that is outside the scope of the delegated driver. What you probably want is to write a molecule-k8s driver, which is easier than you may imagine. Look at existing ones for inspiration https://github.com/topics/molecule-driver
