### ISSUE TITLE
Template/File search behavior when testing playbook / Monolith Repo

### ISSUE THREAD

**Issue by plasticrake** [ansible/molecule#1504]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7
```

```
molecule, version 2.18.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

I'm using molecule to test a playbook as integration/end-to-end testing for a few roles (in addition to testing individual roles, but the issue is only with the playbook testing). I'm having issues with the search path for templates. I'm trying to test a playbook with variables that runs using plain ansible, but fails when using molecule.

The project file structure look like this:
```
/Users/patrick/duplicacy-ansible/molecule/
/Users/patrick/duplicacy-ansible/roles/duplicacy_filter/molecule/
/Users/patrick/duplicacy-ansible/roles/[role-name]/molecule/
...
/Users/patrick/duplicacy-ansible/templates/global.j2
```

When running `molecule converge` from `/Users/patrick/duplicacy-ansible/` it fails to find the templates under `/Users/patrick/duplicacy-ansible/templates/`

For example the `global.j2` template, it fails unless I refer to it as
`../../templates/global.j2` or if I create a symlink from `/Users/patrick/duplicacy-ansible/molecule/default/templates/` to `/Users/patrick/duplicacy-ansible/templates/`.

Is there a way to override the search behavior for this or is symlinking the preferred method for what I'm trying to accomplish?

# Actual Behaviour (Bug report only)

```
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/roles/duplicacy_filter/templates/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/roles/duplicacy_filter/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/roles/duplicacy_filter/tasks/templates/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/roles/duplicacy_filter/tasks/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/molecule/default/templates/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/molecule/default/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/molecule/default/templates/global.j2"
    looking for "global.j2" at "/Users/patrick/duplicacy-ansible/molecule/default/global.j2"

...

 [WARNING]: Unable to find 'global.j2' in expected paths (use -vvvvv to
see paths)

    fatal: [macOS-instance]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: the template file global.j2 could not be found for the lookup"}
```

**Comment by ssbarnea** [comment]
Ansible reports this error, not molecule. If you need you can define environment variables in molecule.yml for helping ansible find the files.

**Comment by plasticrake** [comment]
@ssbarnea From the issue I opened this was only affecting molecule, when using Ansible directly it worked: 
    
> I'm trying to test a playbook with variables that runs using plain ansible, but fails when using molecule.
