### ISSUE TITLE
azure drive not support  rdp connectio

### ISSUE THREAD

**Issue by luupux** [ansible/molecule#1505]
Hi @all  I use molecule test  with azure drive to test things in windows vm 
but I'm little frustrated because molecule login work only with ssh connection, I resolved my issue using some extra script to make a connection but I'm wondering if you like /make sense for molecule project to have an improvement in azure drive to support  RDP and ssh connection.
Other an that any suggestion to manage molecule login with rdp connection are welcome

**Comment by wilmardo** [comment]
Related: #1491  #1488

**Comment by luupux** [comment]
Ok, If I write a patch to support  molecule login in azure drive  may you think to use the code in the molecule ?
If you do that I can work on azure drive otherwise I write a very patch and use it  for my self .

**Comment by wilmardo** [comment]
You could always submit a PR but it is now up to the Ansible dev team to evaluate the PR as @gundalow states in #1491 
So give it a shot! 👍

**Comment by ssbarnea** [comment]
Azure driver is no longer part of the core, please follow https://github.com/pycontribs/molecule-azure for any changes related to it.
