### ISSUE TITLE
Molecule ignores ignoreerrors

### ISSUE THREAD

**Issue by izolight** [ansible/molecule#1520]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.7.0
python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

```
molecule --version
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

If a task is marked with ignoreerrors molecule should ignore them too. (ignoreerrors: true)

# Actual Behaviour (Bug report only)

molecule fails, because an error occured.

**Comment by retr0h** [comment]
It is `ignore_errors` not`ignoreerrors`.
