### ISSUE TITLE
molecule fails during linting destroy when run from inside a virtualenv

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1521]
# Issue Type

- Bug report

# Molecule and Ansible details

```
molecule, version 2.19.0 (pip installed)
```

# Desired Behavior

Molecule shout run the same way if run from inside a virtualenv or from outside.

# Actual Behaviour

At this moment running molecule from outside virtualenv works perfectly. Still, when run from insidea a virtualenv created by tox, it fails with an unclear failure to cleanup after linting.

```
--> Executing Ansible Lint on /Users/ssbarnea/rdo/x/ssbarnea.six/ansible-six/molecule/default/playbook.yml...
Lint completed successfully.
--> Scenario: 'default'
--> Action: 'destroy'

    PLAY [Destroy] *****************************************************************

    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1


ERROR:
An error occurred during the test sequence action: 'destroy'. Cleaning up.
```

**Comment by ssbarnea** [comment]
It seems that this is also easy reproduceable on Travis without any tox involvment. See https://travis-ci.com/ssbarnea/ansible-six

Travis creates a virtualenv for python projects by default, so this bug also affects it.

Any idea why this happens and how to avoid it? ... other than not using virtualenvs.

**Comment by webknjaz** [comment]
Curious, I'll try to take a look at this next week. If not — ping/remind me.

**Comment by wilmardo** [comment]
Could you add the `--debug` flag to molecule and post the output?

**Comment by wilmardo** [comment]
Ran the build myself with `--debug` and the issue is with FreeBSD:
https://travis-ci.org/wilmardo/ansible-six/builds/448855694#L3125 

I tried to run the docker image but it doesn't do a thing:

`docker run -it auchida/freebsd:latest /bin/sh`

Seems to me that the image is broken so will never work 😐 

Also for FreeBSD image to work an install needs to be added for the `pkg`(?) command in the molecule [Dockerfile.j2](https://github.com/ansible/molecule/blob/master/molecule/cookiecutter/scenario/driver/docker/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/Dockerfile.j2)

@ssbarnea If you could provide a working FreeBSD image I should be able to add support 👍

**Comment by webknjaz** [comment]
@ssbarnea 
> reproduceable on Travis [...] I think, there is no virtualenv involved.

That's an incorrect assumption, Travis creates virtualenv by default: https://travis-ci.com/ssbarnea/ansible-six/jobs/154515322#L435

**Comment by webknjaz** [comment]
@ssbarnea it's not clear how you use tox to set up molecule. Could you please drop in some reproducible example?

**Comment by webknjaz** [comment]
In general, this should be working within virtualenv. But maybe Molecule messes up the env somehow...

**Comment by wilmardo** [comment]
@webknjaz In my opinion this is already resolved, look at my comment above.

**Comment by webknjaz** [comment]
I'm not sure. Failures in #1541 @ Travis CI look suspiciously same.

**Comment by webknjaz** [comment]
I think this is also reproducible when running tests in parallel. But needs further confirmation...

**Comment by ssbarnea** [comment]
I managed to narrow it down in https://github.com/ansible/molecule/issues/1888
