### ISSUE TITLE
molecule cannot be called as a module

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1522]
- Bug report

# Desired Behavior

`python -m molecule test` sould have the same result as calling `molecule` script directly.

This is an important aspect because module calling can be used in places where scripts are not installable or not in PATH. Also allows you to control which python version to use to call molecule.

Most python based tools are able to be called like this, including `tox`, `flake8`, ....

The good news is that this feature is very easy to implement, not requiring any special things as python has native support for calling modules as scripts. 

# Actual Behaviour (Bug report only)
```
python -m molecule test
/home/travis/virtualenv/python2.7.14/bin/python: No module named molecule.__main__; 'molecule' is a package and cannot be directly executed
```

**Comment by webknjaz** [comment]
Ref #1545
