### ISSUE TITLE
quay.io Docker image

### ISSUE THREAD

**Issue by gundalow** [ansible/molecule#1532]
Hi,
As part of the repo move we are now building images to https://quay.io/repository/ansible/molecule

These builds will happen automatically now.

Looking for some volunteers to test the new quay.io images and confim they work..

@themr0c I believe you've used the docker images before, would you possibly be able to test them?

Part of https://github.com/ansible/community/issues/366  & https://github.com/ansible/molecule/pull/1531

**Comment by themr0c** [comment]
@gundalow just ran some tests on random roles using 2.19 and latest images from quay. Looks fine.

**Comment by gundalow** [comment]
@themr0c Thank you for confirming.

Considering thisdone.
