### ISSUE TITLE
[TODO] [CI] Figure out ways to re-enable more of skipped tests in CI

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1577]
# Issue Type

- Feature request

# Desired Behavior

In #1541, #1558 and #1561 we've disabled a set of tests primarily in CI or when pre-requisites aren't met. We need to find out a way to still keep that code in a good shape.

Drivers list:
* [ ] Azure
* [x] Docker
* [ ] EC2
* [ ] GCE
* [ ] LXC
* [ ] LXD 
* [ ] OpenStack 
* [ ] Vagrant
* [ ] delegated

**Comment by wilmardo** [comment]
Might be handy to add a list of checkboxes to this issue with tests/modules that are disabled at the moment.

**Comment by lwm** [comment]
From what I understand from: https://github.com/ansible/molecule/blob/241f6b5ed55c9fe48a828a86b02b3574865158cd/test/functional/conftest.py#L67-L75

It is up to driver maintainers now to step up and implement ways in which their tests can be included and excluded? If that is so, should be be pinging maintainers? I'm working on Linode one now.

**Comment by webknjaz** [comment]
@wilmardo it's like... all functional tests except for docker... 

@lwm well, not exactly. We didn't really set up the same flow as in ansible/ansible. And those driver authors contributed changes before repo transfer, without any commitment/thoughts about future maintainership responsibilities. @gundalow was going to ask M$ guys whether they want to help with azure driver, but I don't know about the other ones.

Ideally, we need someone to at least help us find some stubs maybe so that it would be possible to run functional tests without hitting anything on the Internet.
In ansible/ansible we usually end up creating docker images with stub servers simulating real ones in a dumb way. We could try doing the same here.

As for LXC/LXD, I've been experiencing issues with them under Travis CI, but maybe by enabling `sudo: required` it'll work.

**Comment by wilmardo** [comment]
Thanks for the list! I will have a look at the LXD requirements hopefully in the upcoming days.

Might be a good idea to start pinging user who submitted a driver or contributed to it?

@webknjaz `sudo: required` is indeed required, running LXD inside a Docker container does not work for what I tried. See here for an example one of [my roles](https://github.com/wilmardo/ansible-role-plex/blob/lxd-testing/.travis.yml). I mount the socket to the container and use gosu to ensure the user in the container can use the socket without being root ([link](https://github.com/LANsible/ansible-dev-container/blob/master/entrypoint.sh))

**Comment by webknjaz** [comment]
Well, considering that Travis CI is shutting down their container-based infra in favor of VM-only, I was thinking to explicitly migrate right away :)
This'd simplify CI config as well.

**Comment by webknjaz** [comment]
So I've tried to enable LXC, LXD, and Vagrant. All have failed. Any help appreciated :)

**Comment by webknjaz** [comment]
@wilmardo why did you reinstall LXD via snap in your example?
