### ISSUE TITLE
local tox execution gives different results than CI

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1585]
# Issue Type

- Bug report

# Molecule and Ansible details

At this moment is high likely that when a developer runs molecule own "tox" locally he will get different results than on Travis, especially when it comes to linting.

This is caused by the fact that tox fails to check and update the requirements on already created virtualenvs.  The old workaround was to recreated them using "tox -r -e env" but this is costly and also involved a lot of wasted time due to a broken workflows

* run tox locally
* push change
* wait results, see failure,...
* investigate failure: run again locally, wonder...., google, .... 10min later... remembering about tox -r
* pushing fix again...

In the past I used to disable the deps section from tox.ini and replace them with pip install commands but few days ago I found a much better solition at https://github.com/tox-dev/tox/issues/149#issuecomment-433714373 -- which I already implemented in few repositories.

I will make a change request for addressing it, please assign this to me.

**Comment by webknjaz** [comment]
Ok, we can give it a try.

**Comment by decentral1se** [comment]
Is this still an issue @ssbarnea?

**Comment by ssbarnea** [comment]
Yes, still and issue and I plan to look into it. So far I was able to use only unittests and linting envs on tox, on multiple platforms. I am using 3 different OS-es to test MacOS, Centos 7 and Fedora 28 and it failed on all.

This does not mean that I will not appreciate help/comments here. The goal is the most users that would clone of molecule should be able to run "tox" succesfully. If there are any setup requirements it should clearly be visible: either skips due to missing setup or just clear failures.

**Comment by decentral1se** [comment]
Don't think this is an issue anymore.
