### ISSUE TITLE
Cloud provider drivers "lose track" of instances due to writing state to /tmp by default

### ISSUE THREAD

**Issue by danielkza** [ansible/molecule#1589]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.1
  config file = /home/danielkza/.ansible.cfg
  configured module search path = ['/home/danielkza/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/danielkza/cobli/deploy-gravitational-teleport/ansible/venv/lib/python3.6/site-packages/ansible
  executable location = /home/danielkza/cobli/deploy-gravitational-teleport/ansible/venv/bin/ansible
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
molecule, version 2.19.0
```

Both from pip.

# Desired Behavior

Molecule should be able to recall created cloud resources after rebooting the system. Currently state is written to /tmp by default, meaning after a reboot all the instances will be recreated, and old instances will be left over, costing the user money indefinitely.

I observed this with the default EC2 driver, but after a cursory look, it seems the same issue might be present in all drivers.

# Actual Behaviour

Molecule should write resources IDs created in cloud accounts to some permanent state storage, and avoid as much as possible leaving resources to manually clean up after.

**Comment by ssbarnea** [comment]
EC2 Driver was removed from core, add ticket to https://github.com/pycontribs/molecule-ec2 if stil valid.
