### ISSUE TITLE
Docs: testing page contains misleading information

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1595]
I've found untrue information in docs. Now, this is related to testing, but I suspect there may be more. We need to go through docs, verify and fix everything.

# Issue Type

- Bug report

# Desired Behavior

Users can rely on docs.

# Actual Behaviour

LXC/LXD instructions (https://molecule.readthedocs.io/en/latest/testing.html#lxc) ain't true: there's no `test/functional/lxc`/`test/functional/lxd` folders with Vagrantfiles at all. They didn't even exist at the time of the PR #863 adding this info to docs.

**Comment by lwm** [comment]
I've submitted https://github.com/ansible/molecule/pull/1684 which fixes the immediate issue in this report. I don't think it is feasible for us to catch all the documentation issues and not delay the next release for a very, very long time. Can we drop this from the v2.20 milestone?

I should probably link out to https://etherpad.openstack.org/p/ansible-molecule as well. Many documentation issues are being collected there.
