### ISSUE TITLE
Include "pyvmomi" in docker image

### ISSUE THREAD

**Issue by henrik-farre** [ansible/molecule#1597]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package

# Desired Behavior

We use the delegate driver in molecule, and we would like to use the ansible vmware_guest module that depends on the python module pyvmomi, but it is not installed in the default quay.io molecule image.

It should be added to PIP_PACKAGES env in the Dockerfile https://github.com/ansible/molecule/blob/master/build/Dockerfile#L30

**Comment by lwm** [comment]
Hey there, I think this is a case for overriding the default Dockerfile since it serves a narrow use case.

**Comment by henrik-farre** [comment]
Hi @lwm 

That is what we do currently, and we can live with that :)
