### ISSUE TITLE
Cannot pip install extra packages

### ISSUE THREAD

**Issue by elliotweiser** [ansible/molecule#1602]
# Issue Type

- Bug report

Molecule 2.19.0
Ansible 2.7.2

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

`pip install molecule[vagrant]` should install any extra packages indicated by the key `vagrant`, i.e. `python-vagrant`. 

# Actual Behaviour

There are no extra packages installed, which might be a problem with the version of `pbr` used as a setup requirement.

Note that there are no extras shown in https://pypi.org/pypi/molecule/2.19.0/json, which is normally the case for packages that declare extras.

```bash
curl -sSL https://pypi.org/pypi/molecule/2.19.0/json | jq -r '.'
```

**Comment by webknjaz** [comment]
Hi @elliotweiser,

I've added extras to master after the release `v2.19.0`. They haven't reached PyPI yet, thus you're seeing only the distribution version without extras in metadata.

This is not a bug and will be addressed once we publish next release.
