### ISSUE TITLE
Can we update the source repo on `pip show`?

### ISSUE THREAD

**Issue by acozine** [ansible/molecule#1609]
# Issue Type

- Bug report

# Molecule and Ansible details

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- source

# Desired Behavior

When I run `pip show molecule`, the repo listing should point to `github.com/ansible/molecule`.

# Actual Behaviour

```
[alicia@tooticky]~/installed$ pip show molecule
Name: molecule
Version: 2.19.0
Summary: Molecule aids in the development and testing of Ansible roles.
Home-page: https://github.com/metacloud/molecule
Author: UNKNOWN
Author-email: UNKNOWN
License: MIT
Location: /Users/alicia/Library/Python/2.7/lib/python/site-packages
Requires: cookiecutter, flake8, testinfra, anyconfig, tree-format, pbr, PyYAML, click-completion, click, yamllint, six, cerberus, Jinja2, ansible-lint, python-gilt, psutil, tabulate, colorama, pexpect, sh
Required-by: 
```

**Comment by gundalow** [comment]
The links in the repo have been updated, I haven't pushed a new build to PyPI yet.

**Comment by webknjaz** [comment]
And it'll be easier to finally publish that once #1593 is out :)

**Comment by webknjaz** [comment]
@acozine You can preview it from https://test.pypi.org/p/molecule/2.19.1.dev63

**Comment by webknjaz** [comment]
This two are still missing (ref #1616)
```
Author: UNKNOWN
Author-email: UNKNOWN
```
But at least I've added "maintainer" fields.

**Comment by gundalow** [comment]
Fixing author is tracked in https://github.com/ansible/molecule/issues/1616

**Comment by webknjaz** [comment]
Yep, I linked that in my comment :)

**Comment by ssbarnea** [comment]
I propose using same values as Ansible package and if @retr0h complaints later we can always fix. I would be personally more offended if someone would publish my personal email there than not puting it.

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1765 got merged, considering this handled!
