### ISSUE TITLE
Restore author field in distribution metadata

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1616]
# Issue Type

- Bug report

# Desired Behavior

Author field is not present in the metadata which is important to PyPI.
It looks like it'd been removed in this PR: https://github.com/ansible/molecule/pull/411/files#diff-380c6a8ebbbce17d55d50ef17d3cf906L3.

@retr0h is is ok to restore those lines?

# Actual Behaviour

author field is not supplied in `setup.cfg`

**Comment by webknjaz** [comment]
@retr0h?

**Comment by lwm** [comment]
@retr0h, sorry to bump again but we need to this resolved ASAP. Thanks!

**Comment by lwm** [comment]
OK, Github smoke signals are not working. Does anyone have any contact details? Just need a Yes/No.

**Comment by webknjaz** [comment]
@gundalow has his email, I don't

**Comment by gundalow** [comment]
bumping to v2.21, I don't think is blocks release. Please correct me if I'm wrong

**Comment by webknjaz** [comment]
Confirmed. Not a blocker. Rather "nice to have".

**Comment by retr0h** [comment]
I have no idea why I never saw these mentions, but Authors can be changed to whatever you guys want Authors to be changed to.

**Comment by webknjaz** [comment]
@retr0h, in my opinion, it would be fair if "authors" would point to real original authors and "maintainer" would point to Red Hat. What do you think?
