### ISSUE TITLE
DOCS - add gitlab runner configuration example 

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible/molecule#1619]
# Issue Type

- Feature request
https://github.com/ansible/molecule/blob/master/doc/source/ci.rst#gitlab-ci
# Desired Behavior
There would be very helpful for newbies to get the command that the runner is registered to the CI of Giltab. Mainly we miss here the type of executor and various explanations. 

Thanks a lot I was looking for an example for a long time.

**Comment by lwm** [comment]
>  There would be very helpful for newbies to get the command that the runner is registered to the CI of Giltab. 

Sorry, can you clarify?

**Comment by mihai-satmarean** [comment]
Hi, thanks for looking into it,

I meant that someone new to the concept (like me) would still need to go 2 more hours threough documentations and infos to come out with this command. `
gitlab-ci-multi-runner register -n --url https://yourgitlab.com --registration-token HqS3jZitk_Ro7Pyxv7rv --tag-list shell,pip36,docker --executor shell --description 'Shell runner molecule'`

Very good thing!
