### ISSUE TITLE
Doc Clarification  - Expanded description of molecule commands for newcomers

### ISSUE THREAD

**Issue by mechastorm** [ansible/molecule#1620]
I had tried posting this in the mailing list, but I had gotten an error about not being able to send an email out to the group(?). If this is not the appropriate channel feel free to delete this.

I am just picking up on Molecule and I am a bit confused with the commands available in Molecule. 

Could someone help to clarify to me what is do these command actual do? 

- molecule converge - It says to "converge the instances". When I actually ran it, it will do all the instance creation and preparation but not test. So my understanding is that this command will do all the sequences to prepare the test environment BUT not actually test anything?
- molecule test / verify - What is the difference between molecule test and molecule verify? Seems to be "verify" does the actual work of running my tests. Does "molecule test" simply test that the molecule configs can be read?

The one issue I am also having is the documentation on molecule.readthedocs.com is a bit sparse on each command

Example on 'Check' - https://molecule.readthedocs.io/en/2.19/usage.html 
There is no description of what will it do. What is the difference of Check compared to Test and Verify?

It would be good if there would be expanded documentation on what each command is meant to do and what they do in detail. I can help add this if I know this myself.

**Comment by mechastorm** [comment]
Thanks to decentral1se from the IRC room, I have found where in the docs I can get more information
https://molecule.readthedocs.io/en/latest/configuration.html#scenario

The page above does clarify alot, but I will leave this issue open as I think more new users will first go to the "Usage" section first before they will realize they can find that info in the Config section.

**Comment by decentral1se** [comment]
Thanks for feedback @mechastorm! I'm merging this into https://github.com/ansible/molecule/issues/2264.
