### ISSUE TITLE
Execute testinfra against producction servers

### ISSUE THREAD

**Issue by asg1612** [ansible/molecule#1623]
Hi,

I'm trying to figure out how to execute tests (testinfra write on molecule) on production servers.

how I can do it?

**Comment by dj-wasabi** [comment]
It could be considered spam, but I did some of that with this blog post: https://werner-dijkerman.nl/2017/09/17/continuous-deployment-of-ansible-roles/

Maybe that helps?

**Comment by asg1612** [comment]
> It could be considered spam, but I did some of that with this blog post: https://werner-dijkerman.nl/2017/09/17/continuous-deployment-of-ansible-roles/
> 
> Maybe that helps?

Hi dj-wasabi!

I take a quick look to blog post. I think that I'm searching this command.

`sh "testinfra --connection=ansible --ansible-inventory=hosts --hosts='all:!localhost:!staging' ${WORKSPACE_DIR}/ansible-access/molecule/default/tests/test_default.py --verbose"`

Thanks! I'll try it.
