### ISSUE TITLE
Clarify  defaults for LXD source block and means of overriding.

### ISSUE THREAD

**Issue by snesbittsea** [ansible/molecule#1624]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.4
  config file = None
  configured module search path = ['/home/snesbitt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/snesbitt/.local/share/virtualenvs/IAC-5ywJhOcr/lib/python3.6/site-packages/ansible
  executable location = /home/snesbitt/.local/share/virtualenvs/IAC-5ywJhOcr/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

The new create.yml for the lxd driver has a source definition which sets the server to "https://images.linuxcontainers.org". As far as I can tell, this behavior is not documented nor is the means in which to override it (I am grabbing images from my local instance). Through trial and error I eventually figured out I could override the default by setting server to "" (empty string).

It would be nice to have this default documented along with a example of how to use the local LXD image store.

**Comment by wilmardo** [comment]
Thanks for the issue, the reason that the empty string works is that source get combined with a default source in the deafult create.yml. This was done to ensure backwards compatibility with the previous hardcoded values. But now results in unexpected behavior, I will look in a way to fix this or make it more clear in the docs.
I will look into this when I have some free time 👍

**Comment by ssbarnea** [comment]
LXC/LXD was removed from molecule.

**Comment by nkabir** [comment]
LXD was more suitable than Docker to test os-level virtualization. What is the preferred way to test os-level virtualization?

**Comment by snesbittsea** [comment]
Yipes - why was this removed? Most of my Ansible tests rely on LXD for the very reason nkabir mentioned above.

What was the reason for dropping? Can it be reconsidered?

**Comment by ahag93** [comment]
LXD containers, supporting network bridges, macvlan and multiple other options ... I don't think it's a good idea : "LXC/LXD was removed from molecule."

**Comment by ssbarnea** [comment]
@ahag93 If anyone is interested in becoming a maintainer for LXD driver please let me know because in less than hour of work I can take the remove code on a new repo that is installable. The real challenge will be to make it really work.

So those what want to become maintainer the LXD driver, please put a thumb up on this post. I will be happy to bootstrap it for you.

**Comment by nkabir** [comment]
Happy to help but I cannot promise I can get it working given that I am not intimately familiar with molecule internals (yet).

**Comment by ssbarnea** [comment]
@gundalow Please create a new project named `molecule-lxd` near the others and I will takeover boostrapping it from there. Thanks.

**Comment by wilmardo** [comment]
As the author of the last major overhaul I would love to help and try to maintain a LXD driver.
The thing is my work has changed and moved away from Ansible so I am not using LXD testing anymore, but I love to help and keep the driver intact.

This for the same point @ahag93 makes, Docker wasn't sufficient for something simple as roles using the systemd module. I gave an systemd wrapper script a try but that wasn't sufficient and VM's are to resource intensive and slow for quick testing.

**Comment by gundalow** [comment]
@ssbarnea https://github.com/ansible-community/molecule-lxd has been created

@nkabir @wilmardo Thank you for your continued support, it truly is appreciated.
