### ISSUE TITLE
DOCS - docker example doesn't works

### ISSUE THREAD

**Issue by torrentalle** [ansible/molecule#1629]
# Issue Type

- Docs issue

# Docker  details

```
docker --version
Docker version 18.06.1-ce, build e68fc7a
```

# Desired Behavior

The example found in documentation shouldn't be surrounded by single quotes: `'$(pwd)'`

```
docker run --rm -it \
    -v $(pwd):/tmp/$(basename "${PWD}"):ro \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -w /tmp/$(basename "${PWD}") \
    quay.io/ansible/molecule:latest \
    sudo molecule test
```

# Actual Behaviour

Actually, the current snipped fails because `$(pwd)` is evaluated as string due the single quotes.

```
$ docker run --rm -it \
>     -v '$(pwd)':/tmp/$(basename "${PWD}"):ro \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     -w /tmp/$(basename "${PWD}") \
>     quay.io/ansible/molecule:latest \
>     sudo molecule test
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

**Comment by kronenpj** [comment]
IMO, the single quotes should be replaced with double quotes, not removed completely. It's possible the path returned by $(pwd) has spaces which would be retained by double-quoting but not by removing the quotes.

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1728 resolved this AFAICT.
