### ISSUE TITLE
Idempotence test fails while using custom docker

### ISSUE THREAD

**Issue by anis016** [ansible/molecule#1632]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```
ansible 2.7.2
  config file = None
  configured module search path = [u'/home/sayed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sayed/ultra_patch/docker-hive-database/py2.7-venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/sayed/ultra_patch/docker-hive-database/py2.7-venv/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
molecule, version 2.19.0

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

All the test cases should be passed

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour

I created a custom docker, named - `custom-docker` to work with the molecule. Inside the docker Hive is setup and is accessible via Beeline. I wrote the testcase to access the Hive in the docker image and the test case passes.

Next, I created a playbook tasks as follows

```
---
- name: Create Hive database
  hive_database:
    name: "{{ database_name }}"
    ensure: present
```

Where the `hive_database` (I can't enclose full source code) tasks looks something like below.

```
#!/usr/bin/env bash
function create_database {
    beeline -u jdbc:hive2://localhost:10000 --silent=true --showHeader=false --outputformat=csv2 -e "show databases" | grep ${name}

    if [[ $? -eq 0 ]]; then
        changed="false"
        message="Database $name already exists"
    else
        beeline -u jdbc:hive2://localhost:10000 --silent=true --showHeader=false --outputformat=csv2 -e "create database $name"
        changed="true"
        message="Database $name created"
    fi
}
...
...
...
``` 

Now when I run `molecule test` it only shows the below error:

```
ERROR: Idempotence test failed because of the following tasks:
* [custom-docker] => hive-database : Create Hive database
```

**Comment by AlexisLessard** [comment]
Have you tried running your role in a virtual machine? Sometimes, the behaviour in a vm and in a container aren't the same, so that might be a cause. If the role is still not idempotent, maybe the module itself is at fault. I've had issues with the iptables module. I would run it a few time without any changes, but it would always show _changed_, even tough I just added the same rule a few second ago... I'm no expert, but I'm not sure the error is from molecule itself.

**Comment by anis016** [comment]
hy alex! thanks... actually it was an issue with the module that I came across later! it is now working fine. I actually forgot to close the issue though.
