### ISSUE TITLE
[Build an Ansible compatible image fails with fedora:rawhide container

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1645]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.5
  config file = /Users/ssbarnea/.ansible.cfg
  configured module search path = [u'/Users/ssbarnea/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ssbarnea/.pyenv/versions/2.7.15/lib/python2.7/site-packages/ansible
  executable location = /Users/ssbarnea/.pyenv/versions/2.7.15/bin/ansible
  python version = 2.7.15 (default, Oct 17 2018, 20:02:57) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
molecule, version 2.19.1.dev55
```

# Desired Behavior

Image build should suceed on rawhide image.

# Actual Behaviour

The root cause is that `python2-dnf` package no longer exists being replaced by `python3-dnf`. 
Verbose output available at https://gist.github.com/ssbarnea/792000358390a75757b206a2cb38f943

Running molecule in debug mode does give more information
```
No match for argument: python2-dnf
```

To reproduce the problem just try to use this image:
```
platforms:
  - name: fedora-rawhide
    hostname: fedora-rawhide
    image: fedora:rawhide
```

**Comment by MarkusTeufelberger** [comment]
That was one of the reasons for me to write #1642 - that way the installation could be done by Ansible instead of a shell script and it would be also maybe a bit faster to spin up containers (no need to build them first).

**Comment by christiangda** [comment]
Hi everyone,

For my is failing with "Amazon Linux 1" after I update to Ansible  2.8 this morning.

```bash
 TASK [christiangda.epel_repo : Install EPEL repository on Amazon Linux] ********
    fatal: [amazonlinux-1]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "[Errno 2] No such file or directory", "rc": 2}
    changed: [amazonlinux-2]
```

To reproduce it:

**Prepare your environment**
```bash
mkdir ansible-roles
cd ansible-roles/

python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install ansible">2.7" # <-- Fail, pip install ansible"<2.8"  <-- Work
pip install pytest
pip install pytest-mock
pip install pylint
pip install rope
pip install autopep8
pip install yamllint
pip install molecule
pip install docker-py
```
**Clone the role repository and create symbolic link**

```bash
git clone https://github.com/christiangda/ansible-role-epel-repo.git
ln -s ansible-role-epel_repo christiangda.epel-repo
cd ansible-role-epel-repo
```
**Execute the test**

```bash
molecule create
molecule converge
```

**Comment by webknjaz** [comment]
@christiangda if your problem is with installing `Ansible==2.8`, then raise this @ https://github.com/ansible/ansible/issues/new/choose. It doesn't seem to have anything to do with Molecule.

**Comment by webknjaz** [comment]
Also, `docker-py` is outdated. Only use it with Python 2.6. For newer Pythons just `pip install docker`.

**Comment by webknjaz** [comment]
Oh, also parts or your problem seems inconsistent: it looks like you're trying to mix Python 2 and Python 3, which is not a good idea.

**Comment by christiangda** [comment]
Hi everyone,

@webknjaz thank you for your advice, you were right.

I improved my environment now using the following:

```bash
mkdir ansible-roles
cd ansible-roles/

python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install ansible       # <-- ansible 2.8
pip install selinux       # <-- necessary for molecule docker
pip install docker       # <-- your advice
pip install pytest
pip install pytest-mock
pip install pylint
pip install rope
pip install autopep8
pip install yamllint
pip install molecule
```

```bash
git clone https://github.com/christiangda/ansible-role-epel-repo.git
ln -s ansible-role-epel-repo christiangda.epel_repo
cd ansible-role-epel-repo
```

```bash
molecule create
molecule converge
```

**and the error persist**
```bash
    TASK [christiangda.epel_repo : Install EPEL repository on Amazon Linux] ********
    fatal: [amazonlinux-1]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "[Errno 2] No such file or directory", "rc": 2}
    changed: [amazonlinux-2]
```

But if I change the line

```bash
pip install ansible"<2.8"       # <-- ansible 2.7
```

**It work perfectly**

```bash
    TASK [christiangda.epel_repo : Install EPEL repository on Amazon Linux] ********
    changed: [amazonlinux-1]
    changed: [amazonlinux-2]    
```

So the problem is the ansible 2.8 **module yum** with molecule ?
```ansible
...
# My role code
- name: Install EPEL repository on Amazon Linux
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: >
    ansible_os_family == 'RedHat' and
    ansible_distribution == 'Amazon' and
    not epel_repo_file_path_result.stat.exists
...
```

**Comment by christiangda** [comment]
Hi everyone,

As mention @webknjaz the problem is not molecule, is the ansible's module yum.

https://github.com/ansible/ansible/issues/56583

Thanks, everyone

**Comment by decentral1se** [comment]
:+1:

**Comment by webknjaz** [comment]
@christiangda also, you did `pip install selinux` which is not good since it's a semi-fake package by @ssbarnea, what you really want to use is what's distributed with your GNU/Linux distro and also use `--user` with `pip install`.

**Comment by christiangda** [comment]
@webknjaz thank you for your advice!.
