### ISSUE TITLE
allow ansible_args to be set in the provisioner configuration

### ISSUE THREAD

**Issue by singuliere** [ansible/molecule#1650]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.5
  config file = /home/singuliere/software/enough/infrastructure/ansible.cfg
  configured module search path = [u'/home/singuliere/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/singuliere/software/enough/virtualenv-infrastructure/local/lib/python2.7/site-packages/ansible
  executable location = /home/singuliere/software/enough/virtualenv-infrastructure/bin/ansible
  python version = 2.7.15+ (default, Aug 31 2018, 11:56:52) [GCC 8.2.0]
molecule, version 2.16.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

## The problem

An inventory directory may contain multiple inventory files and each of them are loaded when providing the directory to the **--inventory** `ansible-playbook` option. When running **converge** via molecule, the `ansible-playbook` command is provided with a single **--inventory** option pointing to the inventory managed by molecule. It is not possible to set an additional **--inventory** argument with  the [options](https://molecule.readthedocs.io/en/latest/configuration.html#id12) dictionary because it is overridden by molecule and replaced by the inventory managed by molecule.

User story: As a molecule test writer, I want to specify multiple inventory files in `molecule.yml` just as I would be able to specify multiple **--inventory** argument to `ansible-playbook` when called via molecule.

## Proposed solution

Allow for `ansible_args` to be specified in the `provisioner` configuration like so:

```
provisioner:
  name: ansible
  ansible_args:
    - --inventory=../../inventories/common/firewall.yml 
    - --limit=bind-host,bind-client-host,external-host,icinga-host,localhost
```

## Partial workaround

Exactly one additional inventory file can be provided using **i** as an entry in the [options](https://molecule.readthedocs.io/en/latest/configuration.html#id12) dictionary dictionary, because it is equivalent to **inventory**.

However, because `options:`  is a dictionary there is no way to specify the same option more than once and this workaround is only good if adding a single inventory file.

## Related undocumented molecule feature

It is currently possible to append additional ansible-playbook arguments to `converge` via [unprocessed options](https://github.com/ansible/molecule/blob/master/molecule/command/converge.py#L93) like so:

```
molecule converge -s bind --
    --inventory=../../inventories/common/firewall.yml \
    --limit=bind-host,bind-client-host,external-host,icinga-host,localhost
```

**Comment by singuliere** [comment]
this is a duplicate of https://github.com/ansible/molecule/issues/929

**Comment by singuliere** [comment]
However... althouhg #929 allows for something like this

```
molecule converge -s bind --
    --inventory=../../inventories/common/firewall.yml \
    --limit=bind-host,bind-client-host,external-host,icinga-host,localhost
```
it would be more convenient to be able to say the same in the `molecule.yml` file

**Comment by MarkusTeufelberger** [comment]
https://molecule.readthedocs.io/en/latest/configuration.html#id12

`options:` and `confg_options:` already exist, what exactly is the issue here?

**Comment by singuliere** [comment]
> what exactly is the issue here?

There are two issues:

* it is not possible to specify **--inventory** with `options:` or `config_options`
* `options:` or `config_options` being dictionaries it is not possible to specify the same option more than once

in other words the ansible-playbook arguments cannot be expressed with a dictionary: they are a list.
