### ISSUE TITLE
Idempotence test fails ansible alternatives module with slave links

### ISSUE THREAD

**Issue by askb** [ansible/molecule#1667]
# Issue Type

Idempotence test fails while updating JDK11 alternative slave links using ansible roles with molecule. 

# Molecule and Ansible details

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.virtualenvs/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/user/.virtualenvs/ansible/bin/ansible
  python version = 2.7.15 (default, Oct 15 2018, 15:26:09) [GCC 8.2.1 20180801 (Red Hat 8.2.1-2)]

$ molecule --version
molecule, version 2.19.0

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- OS package on CentOS7 / Fedora 29

Detail any linters or test runners used:

# Desired Behavior

Idempotence tests are failing on using alternatives slave links and setting the path.  

# Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

```    
    PLAY RECAP *********************************************************************
    centos7                    : ok=16   changed=8    unreachable=0    failed=0
    ubuntu1604                 : ok=13   changed=9    unreachable=0    failed=0
    
    
--> Scenario: 'default'
--> Action: 'idempotence'
ERROR: Idempotence test failed because of the following tasks:
* [centos7] => java-install : Set javac alternatives
An error occurred during the test sequence action: 'idempotence'. Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
```

code:
```
- name: 'Install OpenJDK {{openjdk11_version}}'
  block:
    - name: 'Fetch OpenJDK {{openjdk11_version}} to /tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
      get_url:
        url: "{{openjdk11_url}}"
        dest: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
        checksum: '{{openjdk11_checksum}}'
    - name: 'Untar OpenJDK {{openjdk11_version}} in /opt/'
      unarchive:
        src: '/tmp/jdk-{{openjdk11_version}}_linux-x64_bin.tar.gz'
        dest: /opt/
        mode: 0755
        remote_src: true
      become: true
      - name: 'Check existing Java setup for OpenJDK {{openjdk11_version}}'
        shell: 'echo "" | alternatives --config java'
        register: alt_config_openjdk11_version
      - name: 'Debug Java Setup'
        debug:
          msg: '{{ alt_config_openjdk11_version}}'
      - name: 'Setup Java master and slave links for OpenJDK {{openjdk11_version}}'
        shell: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-{{openjdk11_version}}/bin/java" 10 \
                  --slave "/usr/bin/jar" "jar" "/opt/jdk-{{openjdk11_version}}/bin/jar" \
                  --slave "/usr/bin/jarsigner" "jarsigner" "/opt/jdk-{{openjdk11_version}}/bin/jarsigner" \
                  --slave "/usr/bin/javac" "javac" "/opt/jdk-{{openjdk11_version}}/bin/javac" \
                  --slave "/usr/bin/javadoc" "javadoc" "/opt/jdk-{{openjdk11_version}}/bin/javadoc" \
                  --slave "/usr/bin/javah" "javah" "/opt/jdk-{{openjdk11_version}}/bin/javah" \
                  --slave "/usr/bin/javap" "javap" "/opt/jdk-{{openjdk11_version}}/bin/javap" \
                  --slave "/usr/bin/javaws" "javaws" "/opt/jdk-{{openjdk11_version}}/bin/javaws"'
        # when: openjdk11_version not in alt_config_openjdk_version
        changed_when: false
        # when: alt_config_openjdk_version.stdout.find(openjdk11_version) == -1
        become: true

```

https://gerrit.linuxfoundation.org/infra/#/c/12944/

https://logs.opendaylight.org/releng/vex-yul-odl-jenkins-1/lf-infra-ansible-roles-tox-verify-any/219/console.log.gz

**Comment by lwm** [comment]
Hi @askb, using `shell: 'alternatives --install` is not an ansible alternatives module but the shell module. The shell module is typically failing idempotence checks when not providing `args: ...` (see [Examples](https://docs.ansible.com/ansible/latest/modules/shell_module.html#examples) for more. I do not understand what this has to do with Molecule. This is just an issue within your playbook to be fixed, no?

**Comment by lwm** [comment]
https://github.com/ansible/molecule/pull/1663 could help!

**Comment by askb** [comment]
> Hi @askb, using `shell: 'alternatives --install` is not an ansible alternatives module but the shell module. The shell module is typically failing idempotence checks when not providing `args: ...` (see [Examples](https://docs.ansible.com/ansible/latest/modules/shell_module.html#examples) for more. I do not understand what this has to do with Molecule. This is just an issue within your playbook to be fixed, no?

@decentral1se: So in the above example code I've provided above is the equivalent of what is achieved using the shell module (and the part which is not supported in alternatives module). Adding support for this option (slave links) in the alternative module with a switch is something that is very useful.

**Comment by decentral1se** [comment]
> Adding support for this option (slave links) in the alternative module with a switch is something that is very useful.

That would be an issue against https://docs.ansible.com/ansible/latest/modules/alternatives_module.html then and not Molecule right? The idempotence run of Molecule is very simple. It just runs your tasks twice and if Ansible reports a change, then it fails. So, this is an issue on your playbook as far as I can tell. I'm going to close this out for now, feel free to re-open! :+1:

**Comment by webknjaz** [comment]
It's basically the same as https://github.com/ansible/molecule/issues/1709#issuecomment-467039463
