### ISSUE TITLE
molecule needs ci added that includes fedora

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1668]
# Issue Type

- Feature request

# Desired Behavior

On openstack we recently we had to introduce testing with fedora-28 platform in addition to our centos-7 in order to prepare the entire chain for the forecoming rhel-8/centos-8 and we discovered a serious of problems with molecule, some fixed after PRs.

Still, this uncovers a much more problematic issue: molecule is not tested on CI with fedora images or VMs.

We need to introduce some minimal testing, at least of the docker images (`fedora:28` and `fedora:rawhide`) in order to spot any possible bugs.

I know that travis has limited testing resources and this affected molecule so before proposing any change I will let the team to consider the best approach for increasing the testing coverage.

It would be enough to prepare an image to validate if it work, somethign that at this moment does not work because of https://github.com/fedora-cloud/docker-brew-fedora/issues/62

**Comment by ssbarnea** [comment]
The purpose: validating the we can build a working molecule docker container based on fedora docker images. Recent bugs proved thart our default Dockerfile was flawed and needed patching in order to make it work on fedora systems.

We don't really need to run much, even an empty playbook would be enough to validate that the builded image worked and that we can connect to it.

See https://github.com/ansible/molecule/pull/1649 -- this being such an example. Now this ticket is about adding a CI test that would allow us to validate that this still works and avoid breaking it regardless if the breakage is caused by a change in molecule or a newer fedora container.

**Comment by webknjaz** [comment]
@ssbarnea do you want to investigate setting it up under the Circle CI? This way we could load-balance our DDoS of CIs :)

**Comment by ssbarnea** [comment]
You can test CentOS, Fedora and probably almost any OS using docker containers, including on Travis. There is no need for real VMs as testing containers works very well for this purpose.

**Comment by ssbarnea** [comment]
I am closing this because now we test installation of the package in Fedora as part of tox "distros" environment.
