### ISSUE TITLE
molecule should infer default scenario name from folder name

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1670]
# Issue Type

- Feature request

# Desired Behavior

When ``scenario.name``  is not mentioned inside `molecule.yaml` file, molecule should assume that its default value is the name of the folder containing the file.

This allow users to reasily rename scenarios without having to change the content of molecule.yml file.

Also this allows users to re-use molecule.yml across multiple scenarios by symlinking it.

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1745 resolved this.
