### ISSUE TITLE
Question: linked_clone for vagrant and virtualbox

### ISSUE THREAD

**Issue by rakhinskiy** [ansible/molecule#1708]
Maybe it's not the best idea to use linked_clone by default for vagrant with virtualbox 
Because https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones say

Note: the generated master VMs are currently not removed automatically by Vagrant. This has to be done manually. However, a master VM can only be removed when there are no linked clones connected to it.

So molecule destroy  can't remove this vms

And provisioner/ansible/plugins/libraries/molecule_vagrant.py :196 ... 
```
      if provider['options']['linked_clone']
        if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
          virtualbox.linked_clone = provider['options']['linked_clone']
        end
      else
        if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
          virtualbox.linked_clone = true
        end
      end
```
Must be?
```
      if provider['options']['linked_clone']
        if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
          virtualbox.linked_clone = provider['options']['linked_clone']
        end
      else
        if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
          virtualbox.linked_clone = false
        end
      end
```
Then I can add to molecule.yml
```
driver:
  name: vagrant
  provider:
    name: virtualbox
    options:
      linked_clone: False
```

**Comment by lwm** [comment]
Hi @rakhinskiy, thanks for the report. I'd like to ask for some further clarifications.

> So molecule destroy can't remove this vms

Can you explain this further? Have you seen this issue in practice. Do you think it's a bug?

Right now, I am not sure how we would test a change to [molecule_vagrant.py](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py) other than manually verifiying that your change works. We're still working on getting a more complete test suite up and running. So, that means, if you want to get something for this merged, you'll have to put more work in :)

So, I'd ask for:
  * An example repository where we can reproduce this issue
  * A PR with your change to `molecule_vagrant.py` that we can then test against the repository mentioned above

**Comment by ssbarnea** [comment]
Need to reopen it at https://github.com/pycontribs/molecule-vagrant/
