### ISSUE TITLE
Review all requirements (functional, build & CI)

### ISSUE THREAD

**Issue by gundalow** [ansible/molecule#1710]
# Issue Type

- Bug report

# Desired Behavior

There are lots of requirement.txt type files where we list a specific version or a range. These all need reviewing, ie https://github.com/ansible/molecule/pull/1695/files/da427d9e19f9b690a6e03cbb4d6c9d240dbd69fd#diff-5120eca88b2f04638db64fb77a95d15c

**Comment by lwm** [comment]
Hmmm, I'm not sure what we should be looking for in this review?

**Comment by themr0c** [comment]
Maybe using pyup or dependabot to automate updates?

**Comment by webknjaz** [comment]
@themr0c `dependabot` seems to be unable to work with `tox.ini` so I'm choosing `pyup`.

**Comment by decentral1se** [comment]
Unsure what is actionable on this and it's been sitting for a looonggg time.
