### ISSUE TITLE
parallel run of unit tests provokes random fails of builds

### ISSUE THREAD

**Issue by themr0c** [ansible/molecule#1713]
# Issue Type

- Bug report

# Actual Behaviour

parallel run of unit tests provokes random fails of builds

```
[gw1] [  0%] ERROR test/unit/test_config.py::test_args_member
```
https://travis-ci.com/ansible/molecule/jobs/174056358
https://travis-ci.com/ansible/molecule/jobs/173856113

parallelism was introduced by this commit:

https://github.com/ansible/molecule/commit/a657ef867e9155ef8108ad8d61492ed416ffb3f2

Should we desactivate parallelism again ? Or fix the test?

**Comment by webknjaz** [comment]
I will merge that but in general I'd like to have tests fixed
