### ISSUE TITLE
`molecule lint` does not match what `ansible-lint .` does

### ISSUE THREAD

**Issue by lwm** [ansible/molecule#1723]
# Issue Type
- Bug report

# Molecule and Ansible details

HEAD and latest release AFAIK.

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

`molecule lint` and `ansible-lint .` behave identically.

# Actual Behaviour

See https://github.com/ansible/molecule/pull/1675#issuecomment-459451002 and https://github.com/ansible/molecule/pull/1675#issuecomment-460098613.

**Comment by lwm** [comment]
Potentially related was https://github.com/ansible/molecule/pull/1722. Basically, the configuration options were not working correctly from the `molecule.yml` (not sure on details) and a `.ansible-lint` had to be introduced to configure `ansible-lint` correctly.

**Comment by Rickkwa** [comment]
Potential blocker for 2.20 release, as having linting break would be a pretty big deal I think.

**Comment by lwm** [comment]
Agreed.

**Comment by lwm** [comment]
Thanks for that fix @pilou-!

**Comment by lwm** [comment]
OK, the fix is merged, awaiting a release which is being tracked at https://github.com/ansible/ansible-lint/milestone/15.

**Comment by Rickkwa** [comment]
Looks like ansible-lint 4.1.0 was released. I ran the commands from my original comment and looks good.

**Comment by gundalow** [comment]
@Rickkwa Thank you for confirming.

**Comment by pilou-** [comment]
@gundalow should not we exclude ansible-lint 4.0.0 and 4.0.1 (from allowed dependencies) ?
