### ISSUE TITLE
Docker upload file

### ISSUE THREAD

**Issue by abedwardsw** [ansible/molecule#1729]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.4
  config file = None
  configured module search path = [u'/homenfs/aedwards/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
molecule, version 2.19.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior
I am using molecule to run ansible tests within docker.

I would like an easy way of uploading test data to the docker container as part of the image build (unless there's a better spot).    I was initially trying to put a "ADD/COPY" command into the Dockerfile, however I couldn't figure out how to get the test data files copied to the molecule_ephemeral_directory so they are available.   Could you possibly provide some details as to the recommended practice to upload some test data to the docker container on build?

My current workaround is to inline the file contents inside the dockerfile, but i'd prefer to upload a external file to improve readability.
```
RUN echo $'\n\
file contents line1\n\
file contents line2' >/tmp/myfile
```

Please give some details of the feature being requested
if there is a better location to do this please let me know.  I was also looking at adding a "create.yml" playbook, but that seems to overwrite the docker create, is there a playbook that I can run after the docker image is built, but not during test execution? 

If you want, I can also update the docs after you give a suggestion, thanks.

**Comment by lwm** [comment]
Hey @abedwardsw, thanks for the report!

> is there a playbook that I can run after the docker image is built, but not during test execution?

Have you seen https://github.com/ansible/molecule/blob/abc4df67cabb27fbb57a6a187bcd99300e59c072/molecule/provisioner/ansible.py#L157? This all sounds like a job for the `prepare.yml`.

**Comment by abedwardsw** [comment]
I missed that, that is exactly what I wanted and it's already documented!  works perfect. thanks for the assistance.

**Comment by lwm** [comment]
We will improve the documentation :)
