### ISSUE TITLE
PyPi uploads failing

### ISSUE THREAD

**Issue by lwm** [ansible/molecule#1730]
# Issue Type
- Bug report

Full logs at https://travis-ci.com/ansible/molecule/jobs/175744500#L1716.
Configuration at https://github.com/ansible/molecule/blob/master/.travis.yml#L369-L393.

**Comment by gundalow** [comment]
```
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File already exists. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/
```

**Comment by gundalow** [comment]
If https://travis-ci.com/ansible/molecule/jobs/175827471 passes we can close this

**Comment by lwm** [comment]
On the latest build, it failed again: https://travis-ci.com/ansible/molecule/builds/101423592. 

So, I'm going to see what I can do to fix this shortly.

**Comment by gundalow** [comment]
```
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File already exists. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/

```

**Comment by lwm** [comment]
I've opened up https://github.com/ansible/molecule/pull/1755 for this.

**Comment by webknjaz** [comment]
FTR I've posted the full analysis of this problem @ https://github.com/ansible/molecule/pull/1755#pullrequestreview-205294580

**Comment by lwm** [comment]
https://travis-ci.com/ansible/molecule/jobs/178902007#L1715 :clap: :clap: :clap:

**Comment by webknjaz** [comment]
Oh, so the problem will reoccur in just 25 commits :)
