### ISSUE TITLE
Add support for DigitalOcean Driver

### ISSUE THREAD

**Issue by bmildren** [ansible/molecule#1735]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.7.6
molecule, version 2.19.1.dev121
```

Molecule installation method (one of):

- source

Ansible installation method (one of):

- pip

# Desired Behavior

Add driver to support for DigitalOcean.

**Comment by bmildren** [comment]
Added PR: https://github.com/ansible/molecule/pull/1736

ofc feel free to make recommendations / requests

**Comment by lwm** [comment]
Oh yes, solid stuff! Digital ocean automation with Molecule is going to be really awesome.

**Comment by gundalow** [comment]
@bmildren I see you've created a PR for this. Excellent thank you. No need to issue first, so I'll close this
