### ISSUE TITLE
Support a standard skip_in_molecule tag 

### ISSUE THREAD

**Issue by JJediny** [ansible/molecule#1742]
# Issue Type
In test-kitchen there is a standard `skip_in_kitchen` tag that can be used with any playbook to automatically detect if the playbook is being run within test-kitchen. After googling, searching the current docs, and looking through issues/PRs I cannot find the equivalent, is there one?

- Feature request
If one does not exist it would be great establish a default ansible arg or tag and mention in the docs so users have a standard way across their playbooks or when using vendored roles without having to add it manually. 

# Molecule and Ansible details
NA
```
ansible --version && molecule --version
```
NA
Molecule installation method (one of):

- source
- pip
- [x]  pipenv

Ansible installation method (one of):

- source
- pip
- OS package

# Desired Behavior
A user could apply a simple conditional to their tasks to detect if the playbook is running within molecule and then skip said task only when being run within molecule. 

Examples - systemd/systemctl calls when using the docker driver.

**Comment by lwm** [comment]
Hi @JJediny, thanks for raising this report. I've got an open PR on improving the documentation which shows a way of skipping tasks using two types of tag: https://github.com/ansible/molecule/pull/1719/files#diff-9169591f4155d8b9f9fe3703d2064a30R5. This is currently hidden (I would say) over at https://molecule.readthedocs.io/en/latest/configuration.html#id13. As far as I understand your report, this is the same functionality and exaclty how I solve the example you gave in the 'Desired Behaviour' section today.

**Comment by JJediny** [comment]
Yes thank you! I confirmed that applying the tag `molecule-notest` to the task(s) successfully skipped a fatal failure on both an Ubuntu 14/16/18 and Centos 6/7 separately. Looking forward to seeing those docs updated with as much

**Comment by lwm** [comment]
:rocket:

**Comment by JJediny** [comment]
@lwm just for clarity is there any difference in the logic of those tags? `molecule-notest` vs `notest`

**Comment by lwm** [comment]
AFAIK, no, it is just to cover different naming preferences. To note, there is also https://github.com/ansible/molecule/pull/1663 coming down the pipes as well.
