### ISSUE TITLE
Update testinfra to avoid incompatibilities with pytest 4

### ISSUE THREAD

**Issue by beenje** [ansible/molecule#1750]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.7
  config file = None
  configured module search path = [u'/Users/benjamin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/benjamin/miniconda3/envs/molecule/lib/python2.7/site-packages/ansible
  executable location = /Users/benjamin/miniconda3/envs/molecule/bin/ansible
  python version = 2.7.15 | packaged by conda-forge | (default, Nov 28 2018, 14:39:28) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Installing molecule via pip forces to install testinfra==1.16.0.
It also installs pytest 4.2.1 which has some incompatibilities with testinfra. See https://github.com/philpep/testinfra/issues/394
It was fixed in testinfra 1.19.0.

I understand this is more a testinfra issue, but the version pinned in molecule should be bumped to avoid incompatibilities.

# Actual Behaviour

```
$ pip install molecule
$ pip freeze
molecule==2.19.0
pytest==4.2.1
testinfra==1.16.0
```

**Comment by lwm** [comment]
Hey @beenje, thanks for raising this! Looks like we need to get this done!

**Comment by beenje** [comment]
Thanks!
