### ISSUE TITLE
pre-commit verifier linter

### ISSUE THREAD

**Issue by dmlb2000** [ansible/molecule#1788]
# Issue Type

- Feature request

# Linting molecule tests

I'd like to have a pre-commit linter to verify my ansible role test suite.

**Comment by MarkusTeufelberger** [comment]
You can run `molecule lint` on your roles I guess...?

Please be a bit more specific with what you'd say would fulfill this feature request.

**Comment by dmlb2000** [comment]
I would like to run https://github.com/pre-commit/pre-commit on the ansible tests, I'm working on a pull request to fix this... shouldn't take long.

**Comment by dmlb2000** [comment]
@MarkusTeufelberger Okay I think I got it to work.

**Comment by MarkusTeufelberger** [comment]
Whyt do you mean by "the ansible tests" - only linting or do you actually want to run `molecule test` as a pre-commit hook?

**Comment by decentral1se** [comment]
Hey @dmlb2000, thanks for the report but I am a bit confused. How would this work? As far as I understand, the pre-commit tool uses `git commit` as the entrypoint and not anything to do with `molecule ...`? Could you further explain?

**Comment by webknjaz** [comment]
@decentral1se you submitted a PR which will cause Molecule to run pre-commit as the part of its flow.

For integration with Git it should be completely different: AFAIR only `hooks.yaml` is needed specifying how to run Molecule from within `pre-commit`.

**Comment by webknjaz** [comment]
Here's the explanation of how to do it: https://pre-commit.com/#new-hooks

**Comment by dmlb2000** [comment]
@decentral1se @webknjaz Yeah there are two ways to integrate molecule with pre-commit and it really depends on who's driving the workflow. To be clear both ways are valid forms of developing software and should be allowed by either software.

 1. The first way is to have `molecule test` drive, whenever there's a step in molecule that is linting the files in the ansible role, `pre-commit` can solve that problem. So it's perfectly valid to add code to molecule that will run `pre-commit`, the command, to perform the linting step. (this is what this pull request is about).

 2. The second way is to have `pre-commit` drive and whenever someone tries to `git commit` new code into their ansible role, `pre-commit` would run and call out to `molecule test`. I tries submitting a request to get a hooks repository made (https://github.com/ansible/molecule/issues/1453) but was told to pound sand.

**Comment by decentral1se** [comment]
Thanks for clarifying @dmlb2000. 2) still sounds a bridge too far but maybe I'm wrong, and certainly, there are more voices in this project to guide than me! So, I leave that for others to comment. I will take a pass on your PR :+1:

**Comment by webknjaz** [comment]
@dmlb2000 @decentral1se +1 for (2). It makes sense, I'd accept a PR for that. It's a typical way of providing a pre-commit hook declaration.
