### ISSUE TITLE
Fix building a docker image and installing molecule from source

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1790]
# Issue Type

- Bug report

# Molecule and Ansible details

```
master
```

Molecule installation method (one of):

- docker

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I want a molecule in the image to be installed from the corresponding source code.

# Actual Behaviour

It is installed from whatever is the latest non-pre version on production PyPI.

```console
➜ docker run -it quay.io/ansible/molecule:v2.20.0a1 bash
Unable to find image 'quay.io/ansible/molecule:v2.20.0a1' locally
v2.20.0a1: Pulling from ansible/molecule
169185f82c45: Already exists 
34c29055ee42: Already exists 
29802c64cdfc: Already exists 
bebe6d49c797: Already exists 
32d22b42c09e: Already exists 
c2c2284587d0: Already exists 
e92ceb70fb83: Already exists 
2e73e8c1bfd2: Already exists 
ee0b89129978: Already exists 
cf94363eed74: Already exists 
79cd903140e9: Pull complete 
Digest: sha256:91331287c907de523b88a509e556eaca2bd5609dd324c15fbb20eb83ea61084b
Status: Downloaded newer image for quay.io/ansible/molecule:v2.20.0a1
bash-4.4$ molecule --version
molecule, version 2.19.0
```

**Comment by decentral1se** [comment]
I've been told a fix is on the way! Thank you @webknjaz :)

**Comment by decentral1se** [comment]
@gundalow, you should be able to make a new pre-release now?
