### ISSUE TITLE
Docs should not state that we support Ansible 2.4 which is EOL

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1812]
# Issue Type

- Bug report

# Molecule and Ansible details

N/A

# Desired Behavior

Docs should say we support Ansible>=2.5

# Actual Behaviour

Docs say we support Ansible>=2.4

**Comment by decentral1se** [comment]
Improvement to be made: https://github.com/ansible/molecule/pull/1814#discussion_r264278773.

**Comment by decentral1se** [comment]
Fixes for this have lead to https://github.com/ansible/molecule/issues/1822 being raised.
