### ISSUE TITLE
molecule testing should skip any drivers that are not configured by default

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1821]
Currently running functional testing on a machine takes forever even if the user has only docker configured. 

We need to assure that all testing drivers that are not configured (azure, lxc, openstack,ec2,...) are skipped almost instantly by default.

**Comment by decentral1se** [comment]
Agreed!

Kinda related: https://github.com/ansible/molecule/issues/1758.

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1870 closes this for now.

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1870 is merged! Gonna close this off for now.
