### ISSUE TITLE
[Documentation] Show latest stable version of documentation

### ISSUE THREAD

**Issue by Lirt** [ansible/molecule#1834]
# Issue Type

[Molecule documentation](https://molecule.readthedocs.io) by default shows `latest` (2.20x) docs instead of `stable` (2.19x).

# Desired Behavior

Since majority of people are using latest stable version (2.19) of molecule (distributed officially by `pip`, `docker` or package managers), we should by default show this (`stable`) version of documentation.

# Actual Behaviour

Documentation showed is for latest branch (master, or pre-release?), which is used only by small portion of users. This can lead people to using features, that are not currently implemented, or merged into oficially distributable release, that most of the people are using. (as I fooled myself today with `cleanup` feature).

**Comment by decentral1se** [comment]
Yeah, I actually think this is really important @Lirt! A  number of reports have been confusing because the reporter was using `latest` vs. `2.19` or whatever and I think we should definitely avoid this.

@gundalow do you have access permissions for this?

I don't see a configurable in https://github.com/ansible/molecule/blob/master/.readthedocs.yml for this.

**Comment by decentral1se** [comment]
Regarding the final paragraph in https://github.com/ansible/molecule/issues/1849#issuecomment-476153969, I am wondering if there is a tradition of `latest` in the world of RTD referring to latest stable? I am not sure what we want to do here (maybe match our docker tags convention!?) but let's keep that in mind.

**Comment by Lirt** [comment]
I was also thinking about the naming convention that we were discussing in [docker tags issue](https://github.com/ansible/molecule/issues/1818). 

I think it would be great to follow the same convention here.

**Comment by decentral1se** [comment]
Here's an example where this bit us: https://github.com/ansible/molecule/issues/1845.

**Comment by decentral1se** [comment]
ping @gundalow, any idea how we can get this done?

**Comment by gundalow** [comment]
Currently, Molecule doesn't have any branches
RTD's displays what's in branch `master`

**Comment by gundalow** [comment]
Might be able to use https://docs.readthedocs.io/en/stable/versions.html so we just use the last tagged version.

**Comment by gundalow** [comment]
Hi,

I've set `stable` as the default doc when you visit molecule.readthedocs.org

So today that means stable = `99e03ea1`, which is the SHA of 2.20, which is the current release.

@Lirt Does that seem good to you?

**Comment by Lirt** [comment]
Hi @gundalow,

it loads `stable` version for me by default, so I guess it is good now. 

Thank you.

**Comment by decentral1se** [comment]
Maximum stoke, thanks all!
