### ISSUE TITLE
Missing cookiecutter/ directory when building from source tarball

### ISSUE THREAD

**Issue by zingyb** [ansible/molecule#1843]
# Issue Type: Bug report

# Molecule and Ansible details

```
ansible 2.7.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/brett/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]

```

Molecule versions affected: 2.19

Molecule installation method: source

Ansible installation method (one of): OS package (Arch Linux)

# Desired Behavior

```sh
[~/usr/lib/python3.7/site-packages/molecule]$ tree -L 1
.
├── command
├── config.py
├── cookiecutter
├── dependency
├── driver
├── __init__.py
├── interpolation.py
├── lint
├── logger.py
├── migrate.py
├── model
├── platforms.py
├── provisioner
├── __pycache__
├── scenario.py
├── scenarios.py
├── shell.py
├── state.py
├── status.py
├── util.py
└── verifier
```

Note that `cookiecutter/` is present

# Actual Behaviour

```sh
[~/usr/lib/python3.7/site-packages/molecule]$ tree -L 1
.
├── command
├── config.py
├── dependency
├── driver
├── __init__.py
├── interpolation.py
├── lint
├── logger.py
├── migrate.py
├── model
├── platforms.py
├── provisioner
├── __pycache__
├── scenario.py
├── scenarios.py
├── shell.py
├── state.py
├── status.py
├── util.py
└── verifier
```

Note the absence of `cookiecutter/`

## Explanation

When building Molecule with `python setup.py build && python setup.py install --root="${pkgdir}" --optimize=1 --skip-build`, I have found that the `cookiecutter/` directory is only installed when using a git checkout of the code. If I use one of the tarballs in the release page, the `cookiecutter/` directory is absent, causing errors when trying to use Molecule after install:
```
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "/usr/lib/python3.7/site-packages/molecule/command/init/../../cookiecutter/scenario/driver/docker" could not be found in the following locations:

/usr/lib/python3.7/site-packages/molecule/command/init/../../cookiecutter/scenario/driver/docker
/usr/lib/python3.7/site-packages/molecule/command/init/../../cookiecutter/scenario/driver/docker
```

**Comment by zingyb** [comment]
I forgot to add: the latest master commit is also affected.

**Comment by decentral1se** [comment]
Thanks for the report @zingyb! I think this is a similar issue to https://github.com/ansible/molecule/issues/1753 and the solution proposed in https://github.com/ansible/molecule/pull/1754 may also work for this.

**Comment by webknjaz** [comment]
I believe this is no longer relevant.
