### ISSUE TITLE
Allow to specify another name for `molecule.yml`

### ISSUE THREAD

**Issue by kuty22** [ansible/molecule#1904]
# Issue Type

- Feature request

# Desired Behavior
Allow to specify another name for `molecule.yml`,

> Example : `molecule --molecule-file=molecule-CI.yml test`

My needs were to be able to run 'molecule test' with docker on my local host (development of my role) and change the platform when it's on my CI (my CI use openstack to run molecule test).

Do you think this could be a good improvement to molecule ?

**Comment by zeitounator** [comment]
Unless I got you wrong, it looks like your specific need could be implemented through scenarios sharing the same resources (playbook...): `molecule test` locally, `molecule test -s default-ci` on CI.

**Comment by decentral1se** [comment]
What @zeitounator said! Yep, scenarios should be used for this. I wouldn't want to allow to customise the `molecule.yml` just yet without a more concrete need (would affect a number of places in the code base for not much reason ...). I would probably lean towards closing this off ...

**Comment by decentral1se** [comment]
Maybe this is docs issue!? 

@kuty22, do you think we could explain this better on https://molecule.readthedocs.io/?

**Comment by kuty22** [comment]
Hello thanks for your answers,that is exactly what I need. I wasn't seen this feature.
Thanks again for your help.
