### ISSUE TITLE
[Discussion] It's a call for consideration to get rid of `tox.ini`

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1921]
# Proposal: Declare 

*Author*: Sviatoslav Sydorenko <@webknjaz> IRC: @webknjaz

*Date*: 2019-04-10

- Status: New
- Proposal type: testing
- Estimated time to implement: 0.5 day

## Motivation

Just because I can :)

### Problems

Having multiple processes-related config files is sometimes overwhelming.

## Solution proposal

It's possible to move the whole contents of `tox.ini` under the `[tool.tox]` section in `pyproject.toml` (recommended as a consolidation of tool configs via PEP 517/518).
Ref: https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini
<details>
<summary>Example</summary>

[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py27,py36

[testenv]
deps = pytest >= 3.0.0, <4
commands = pytest
"""
</details>

Downsides include:
- need to already have `pyproject.toml`-aware version of tox on dev machines
- needs inlining which will break syntax highlighting and will probably make automatic config management painful...

## Dependencies (optional)

N/A

## Testing (optional)

N/A

## Documentation (optional)

We'll have to document the need for the latest tox. 

## Anything else?

N/A

**Comment by decentral1se** [comment]
> needs inlining which will break syntax highlighting and will probably make automatic config management painful...

To check that I understand it correctly: it means we are wrapping our configuration in some """ ... """ mutli-line string or? Could you please give an example of a configuration and what we'll be dealing with? Will be easier to judge.

**Comment by webknjaz** [comment]
@decentral1se use the link in the post

**Comment by webknjaz** [comment]
But since I'm planning to enable bots on this which will probably fail to work with deps declared there I think this one will have to be postponed or temporary rejected anyway.
I just wanted to document this possibility FTR.

**Comment by decentral1se** [comment]
Ah OK, missed it, woops. Any links / estimates on the native implementation (mentioned in https://tox.readthedocs.io/en/latest/example/basic.html#pyproject-toml-tox-legacy-ini)?

**Comment by ssbarnea** [comment]
I am against this idea until we no longer need to use inline ini-in-ini approach. I would also want to see few other well known python projects adopting the new format.  Molecule is already bleading-edge on its own.

Once we have at least 2-3 of our own dependencies already migrated to it, we can follow them.

**Comment by webknjaz** [comment]
Fair enough.
