### ISSUE TITLE
Fixing the released version metadata

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1922]
It's a follow-up for https://github.com/ansible/molecule/pull/1895#pullrequestreview-224227936:
> I haven't done any manual testing of this but it looks good to me now! I know that this has the possibility to resolve a number of issues for the package (and also to push forward re-release 2.20.0 -> 2.20, right!?), so am happy to see this move forward.

1) It's not possible to replace dists in a published version @ PyPI
2) It's possible to remove certain version but not re-upload things in the same place
3) It's also bad to do such replacements
4) Maybe it's possible to upload just `2.20`, maybe not, but we shouldn't do this. For `pip install molecule==2.20` it matches both `2.20` and `2.20.0`. But this will create collisions for users who have allowed hashes saved mapped to the version.
5) We should upload something slightly higher than `2.20`, I think `2.20.post0` would do. See PEP 440 for Python versioning recommendations.
6) We can also remove `2.20.0` but it will break things for people who have it pinned like this. Maybe we should do announcements before such removal or maybe just keep it there as it seems harmless.

```python
In [1]: from packaging import version         
                                                                                          
In [5]: version.parse("2.20.0") == version.parse("2.20")                                                                                
Out[5]: True

In [7]: version.parse("2.20.0") < version.parse("2.20.post0")                                                                           
Out[7]: True
```

For publishing `2.20.post0` I will make a branch from the tag `v2.20.0` and then I will cherry-pick 5314ebd1ae6e5413137eef8d3f7be505e0c847f1 on top of it. Finally, I'll be able to tag that commit to initialize the release process.

**Comment by webknjaz** [comment]
Closing since it's been decided that we should just publish `v2.20`

**Comment by gundalow** [comment]
publish `2.21` (no leading `v`), and jump a release

**Comment by webknjaz** [comment]
@gundalow with and without prefix would work
