### ISSUE TITLE
[BUG] tox currently doesn't parse deps with comments well

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1973]
I'll need to check pyup docs on whether we could post that comment one line above or smth.
I've also filed a bug in tox: https://github.com/tox-dev/tox/issues/1260

TODO:
* [ ] restore filters once it's fixed

---------------------
oh.. this one seems wrong because it's parsed as a single line. we should turn it into a list

_Originally posted by @webknjaz in https://github.com/ansible/molecule/pull/1958_

**Comment by webknjaz** [comment]
https://github.com/tox-dev/tox/pull/1262 will fix this issue once merged.

**Comment by decentral1se** [comment]
OK, this appears to be the reason for our broken CI right now. I assume waiting for a release of Tox will take too long, so is there a stop gap fix we can put in place now to get us back to a running CI without this issue?

**Comment by decentral1se** [comment]
How about https://github.com/ansible/molecule/pull/1977 for now?

**Comment by webknjaz** [comment]
Good news! We'll be able to address this soon!
