### ISSUE TITLE
Update release procedure

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1981]
Hmmmm, we should probably not make releases without following some process

@webknjaz, would you mind to update the release documentation?

_Originally posted by @decentral1se in https://github.com/ansible/molecule/pull/1967#issuecomment-483565269_

**Comment by gundalow** [comment]
The process is https://molecule.readthedocs.io/en/stable/development.html#release-engineering (which may need updating)

**Comment by webknjaz** [comment]
Yep, it also mentioned Makefile which isn't there anymore.

*/me wishes he could automate this part faster...*
