### ISSUE TITLE
Emojis in default template don't render in browser

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/molecule#1987]
# Issue Type

- Bug report

# Molecule and Ansible details

# Desired Behavior

As few emojis as possible in my GitHub experience. They look infantile, only add visual noise with 0 benefits and don't render nicely in many fonts.

# Actual Behaviour

The character before the "Bug report" GitHub issue type doesn't render in my browser (just like the emojis in front of the other issue types), I only see a rectangle. Even if it would render, Emoji support in standard fonts used in browsers is usually weak.

See https://i.imgur.com/zMSwxBa.png for an example.

**Comment by webknjaz** [comment]
@MarkusTeufelberger it's just like any other unicode chars: they are rendered as long as you have a proper font set up in your system. There's nothing we can do.

For those who can see them, it's a clear indication of what the lines are about and it's easier to jump to the proper line. For others, it looks more or less like bullet points which seems fine as well.

**Comment by seandst** [comment]
> There's nothing we can do.

Not entirely true. We could choose not to use emoji.

> For those who can see them, it's a clear indication of what the lines are about and it's easier to jump to the proper line. For others, it looks more or less like bullet points which seems fine as well.

I can see them, but for me they are not a clear indication of what the lines are about. Instead, they're just distracting, and make it slightly more difficult for me to find the issue type I'm looking for.

**Comment by webknjaz** [comment]
> We could choose not to use emoji.

I mean on the client side there's nothing to do for us...

> distracting, and make it slightly more difficult

I truly don't understand this. But that's because we're likely from different generations :)

**Comment by decentral1se** [comment]
This is a dangerous https://shed.bike/.

Just submit a PR to remove them (I don't care) or close this off.

We've got bigger fish to fry people.

**Comment by webknjaz** [comment]
I want to see pictures. They are helpful to me.

**Comment by MarkusTeufelberger** [comment]
Fixed in #2074
