### ISSUE TITLE
DCO requirement isn't checked for members of the Ansible organization

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/molecule#1988]
# Issue Type

- Bug report

# Desired Behavior

According to the "contribution guidelines", every contribution must be signed off.

# Actual Behaviour

Current Red Hat employees are not checked for including that stuff in their commit messages:
https://github.com/ansible/molecule/blob/master/.github/dco.yml

See https://github.com/probot/dco#skipping-sign-off-for-organization-members

**Comment by webknjaz** [comment]
@MarkusTeufelberger FYI "Red Hat" is spelled as two words separated with whitespace.

**Comment by gundalow** [comment]
Just to clarify, the `members:` in this case means people with commit on this repo.

**Comment by MarkusTeufelberger** [comment]
I understood it as "every member of the Ansible organization on Github"...?

Anyways, the contribution document clearly states that every commit must be signed-off.
