### ISSUE TITLE
Contributors.md Governance updates

### ISSUE THREAD

**Issue by gundalow** [ansible/molecule#1992]
# Issue Type

- Bug report

# Desired Behavior

Form IRC Meeting 2019-04-17 add Contirbuting/governance docs

1) If your PRs get stuck join us in IRC or add to agenda
2) Coding standard is what's enforced by CI, everything else is off topic
3) All PRs must be reviewed by one other person. This is enforced by GitHub
Larger changes require +2

Also, take the time to tidy up `CONTRIBUTING.md`

**Comment by MarkusTeufelberger** [comment]
Because it is not yet explicitly mentioned in this repository:
COC is the one from the Ansible project at https://docs.ansible.com/ansible/latest/community/code_of_conduct.html

**Comment by webknjaz** [comment]
@MarkusTeufelberger it is: https://github.com/ansible/molecule/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by decentral1se** [comment]
I've updated the WG page to point to the CoC (see https://github.com/ansible/community/wiki/Molecule#code-of-conduct) and submitted https://github.com/ansible/molecule/pull/2036 to push this along.
