### ISSUE TITLE
Sort out image blobs in the repo

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#2003]
It'd widely known that having blobs in the Git tree is harmful in general (because of Git's design).

`/asset/molecule.png` and `/doc/source/_static/logo.png` are the same file duplicated in the repo.
`/asset/mollie.png` is used nowhere.
`*.psd` files are big blobs.

This can be improved:

0) Don't keep duplicates in the repo
1) Use SVG for web pages
2) Try to check whether there's any useful metadata in those Photoshop sources; If not, having an image in vector format should be more than enough. If yes, it should be mostly possible to extract that metadata and put into SVG files.
3) Eliminate PNG in favor of SVG (which are XML documents essentially == text which is Git-friendly)

# Issue Type

- Bug report

# Molecule and Ansible details

N/A

Molecule installation method (one of):

N/A

Ansible installation method (one of):

N/A

Detail any linters or test runners used:

N/A

# Desired Behavior

No blobs in Git tree.

# Actual Behaviour

Blobs in Git tree.

**Comment by MarkusTeufelberger** [comment]
Short of a full history rewrite these blobs will remain anyways.

**Comment by webknjaz** [comment]
@MarkusTeufelberger yes, but I'm not advocating for the rewrite. Those things are not needed in the dev checkout + they are not needed in dists. This will also allow us to remove `MANIFEST.in` which I had to add because current artifact tracking relies on Git-tracked files.

Also, when the need arises to change those artifacts, each change will generate megabytes of the Git tree growth which won't happen with text content.
