### ISSUE TITLE
Editable mode is not supported for pyproject.toml-style projects.

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2006]
For Tox 3.9.0, I see now the following when running the unit tests:

> ERROR: Error installing 'file:///home/decentral1se/ansible/molecule': editable mode is not supported for pyproject.toml-style projects. This project is being processed as pyproject.toml-style because it has a pyproject.toml file with a "build-backend" key in the "build_system" value. See PEP 517 for the relevant specification.

The fix is to set `usedevelop = False` and not do any `pip install -e` stuff. 

What do you think @webknjaz.

**Comment by decentral1se** [comment]
Wait a second, this is a Pip thing which Tox is reporting. Pip version 19.1

**Comment by decentral1se** [comment]
CI on https://github.com/ansible/molecule/pull/1811 is blocked by this.

**Comment by webknjaz** [comment]
We can temporarily downgrade pip in tox.

Refs:
- https://github.com/pypa/pip/issues/6434
- https://github.com/tox-dev/tox/issues/1276

**Comment by webknjaz** [comment]
@decentral1se let's just have https://github.com/ansible/molecule/pull/2009 for now. Hopefully, tox will provide a native workaround soon and we'll just remove this hack.
