### ISSUE TITLE
yamllint from the molecule virtualenv isn't found

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#2012]
```console
--> Executing Yamllint on files found in /tmp/mol-test/webknjaz.coll/...
pyenv: yamllint: command not found

The `yamllint' command exists in these Python versions:
  3.7.0
  3.7.1/envs/ansible-opencanary-py3.7.1-pyenv-venv
  3.7.1/envs/molecule_error_example-py3.7.1-pyenv-venv
  3.7.1/envs/molecule-py3.7.1-pyenv-venv
  ansible-opencanary-py3.7.1-pyenv-venv
  molecule_error_example-py3.7.1-pyenv-venv
  molecule-py3.7.1-pyenv-venv

An error occurred during the test sequence action: 'lint'. Cleaning up.
```

Possible solutions:
1) explicitly use the same Python interpreter:
```python
import sys
import sh
getattr(sh, sys.executable).bake(  # instead of `sh.yamllint.bake(`
    '-m', 'yamllint',
    ...
```
2)
```python
import yamllint
```

# Issue Type

- Bug report

# Molecule and Ansible details

master

Molecule installation method (one of):

- source

Ansible installation method (one of):

- pip

# Desired Behavior

Molecule picks up yamllint from the same virtualenv

# Actual Behaviour

Molecule executed from a virtualenv uses `sh` module and fails to find `yamllint` installed right next to it.

**Comment by webknjaz** [comment]
Ref: https://github.com/ansible/molecule/issues/1851#issuecomment-487067137

**Comment by webknjaz** [comment]
Alright... This seems to affect all `sh` invocations.

**Comment by webknjaz** [comment]
After all, this will probably turn into subprocess invocation refactoring...

**Comment by decentral1se** [comment]
Oh dear me, this is a huge breakage ... taking a look, thanks for raising.

**Comment by decentral1se** [comment]
Data point on `sh`:  "Latest commit 858adf0 on 9 Jun 2017"

https://github.com/amoffat/sh

**Comment by decentral1se** [comment]
Wait a second ... `pip freeze ` after a `pip install .` reports that yamllint is not there!?

We never included this in `install_requires`? It was transitive before or?

I opened up https://github.com/ansible/molecule/pull/2033 to start this conversation ...

**Comment by webknjaz** [comment]
@decentral1se it's reproducible if you use an absolute path to the executable in virtualenv without activating that virtualenv. So since `sh` relies on PATH it doesn't work which is ridiculous...

I've talked to a few folks at PyCon and we all agreed that this lib is pointless and everyone should keep a distance from it: it relies on magical implicit behavior which results in mysterious side-effects. I've hit first problems with it immediately after the Molecule acquisition but haven't paid much attention to it since I was busy fixing other stuff.

Now it's absolutely clear to me that it's better to get rid of `sh`. Also, we need to re-evaluate how subprocesses/tasks are supposed to be called.

**Comment by decentral1se** [comment]
> get rid of sh. Also, we need to re-evaluate how subprocesses/tasks are supposed to be called.

I'm fine with this.

**Comment by decentral1se** [comment]
Done for now in https://github.com/ansible/molecule/commit/023bef688cc4e78301ec81cf3df42919f9817d08.
