### ISSUE TITLE
Dependencies too constrained

### ISSUE THREAD

**Issue by micheelengronne** [ansible/molecule#2023]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible-2.7.10
molecule-2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

Tests run on a Docker ubuntu:bionic with python3.6

The command is:

    pip3 install --upgrade -r requirements.txt

the requirements.txt file contains:

```
ansible
ansible-lint
ansible-bender
molecule
yamllint
docker
```

# Desired Behavior

pip dependencies should be resolved without any conflict.

# Actual Behaviour

the install gives:

```
ERROR: molecule 2.20.1 has requirement Jinja2==2.10, but you'll have jinja2 2.10.1 which is incompatible.
ERROR: molecule 2.20.1 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.
ERROR: molecule 2.20.1 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.
ERROR: molecule 2.20.1 has requirement tabulate==0.8.2, but you'll have tabulate 0.8.3 which is incompatible.
```

molecule constraints its dependencies too much as dependencies with newer minor versions (Semver syntax) conflict.

**Comment by decentral1se** [comment]
See https://github.com/ansible/molecule/issues/1831 (this is probably a duplicate).

**Comment by micheelengronne** [comment]
Yep.
