### ISSUE TITLE
Add support for InSpec reports

### ISSUE THREAD

**Issue by metmajer** [ansible/molecule#2027]
# Issue Type

- Feature request

# Desired Behavior

I would like to see support for configuring InSpec's _reporter_ feature at https://www.inspec.io/docs/reference/reporters/, which we currently use with Test Kitchen to create compliance reports out of raw JSON test results generated by the InSpec reporter. It appears that Molecule does not support configuring the InSpec reporter yet.

**Comment by metmajer** [comment]
I went through the documentation at https://molecule.readthedocs.io/en/stable/configuration.html#inspec again and came across the following remark: "Additional options can be passed to inspec exec by modifying the verify playbook." This sounds like a solution to the problem. Could someone please add or link to an example in the documentation as a viable solution?

**Comment by themr0c** [comment]
Hi, we have very few (declared) inspec users in the community. As you have some usecase where you can validate the best approach, would it make sense to you to write this improvement proposal? It would be much appreciated!

(NB: I have been one of the inspec users, but currently I am not, which would make my input less valuable)

**Comment by decentral1se** [comment]
Migrated to https://github.com/pycontribs/molecule-inspec/issues/1.
