### ISSUE TITLE
linting and testing virtualenv

### ISSUE THREAD

**Issue by ratmav** [ansible/molecule#2039]
# Issue Type

- Bug report

# Molecule and Ansible details

```
[user@host dir]$ pipenv run ansible --version
ansible 2.7.8
  config file = None
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user/.local/share/virtualenvs/project_name-F5AQQX11/lib/python3.7/site-packages/ansible
  executable location = /Users/ccuming/.local/share/virtualenvs/project_name-F5AQQX11/bin/ansible
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
[user@host dir]$ pipenv run molecule --version
molecule, version 2.19.0
```

Molecule installation method (one of):
- pipenv

Ansible installation method (one of):
- pipenv

Detail any linters or test runners used:

# Desired Behavior

when i run molecule tests, i'd like the virtualenv's packages (ansible and molecule) to not be scanned.

# Actual Behaviour

when i run molecule tests, the virtualenv packages are being scanned via flake8 and testinfra.

Include a [minimum complete verifiable example](https://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

Pipfile

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
ansible = "*"
molecule = "*"
docker-py = "*"

[requires]
python_version = "3.7"
```

[molcule_debug.log](https://github.com/ansible/molecule/files/3168130/molcule_debug.log)

i tried passing `exclude=*/virtualenvs/*` to flake8, but that didn't quite get it. is there something else i can try?

**Comment by decentral1se** [comment]
Hi there. 

`pipenv` is an unsupported install method and in my experience, if you have any packages (like `flake8` in this case) intalled outside of the `pipenv` managed environment you should double check that the right `flake8` executable is being used ... that is one thing to think about ...

The other is, you haven't provided a configuration but have you configured `flake8` with the standard `molecule.yml` method: https://molecule.readthedocs.io/en/stable/configuration.html#root-lint? Or you're using another configuration file?

**Comment by ratmav** [comment]
pretty sure flake8 is in the venv. `which flake8` only finds something when i prepend `pipenv run`. 

i noticed pipenv isn't mentioned in the docs. it made me a little sad, since afaik pipenv is the "official" tool now. i'm not stepping into that flame war (poetry, pipenv, etc.), i'm just using it since it's the direction the community seems to be going at the moment. given the controversy, and i didn't see pipenv in the docs, i kinda figured that's what it was.

thanks for the heads up about the flake config. i was looking for something like that before, but must have missed it. i can try it and see if it helps. official pipenv support would be nice to have, however.

**Comment by decentral1se** [comment]
> i'm not stepping into that flame war

You've already put one foot in the door ... good luck!

**Comment by ratmav** [comment]
i'll see if i can hack a way to make this work better on my end. if it requires a mr, would you be interested, @decentral1se?

**Comment by ssbarnea** [comment]
This seems as an unsupported use-case so I will be closing. Still, if you find a way to avoid it, you are welcomed to make a PR.
