### ISSUE TITLE
need Sysctl parameter to add into container while running container

### ISSUE THREAD

**Issue by thatsk** [ansible/molecule#2048]
# Issue Type

- Feature request

Molecule and Ansible details

dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nocon01p2
    hostname: nocon01p2.example.com
    image: centos/systemd:1.0
    pre_build_image: True
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    networks:
      - name: example.com
  - name: nocon02p2
    hostname: nocon01p2.example.com
    image: centos/systemd:1.0
    pre_build_image: True
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    networks:
      - name: example.com
  - name: nocon03p2
    hostname: nocon01p2.example.com
    image: centos/systemd:1.0
    pre_build_image: True
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    networks:
      - name: example.com
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8

ansible --version 
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
molecule --version
molecule, version 2.20.1

Molecule installation method :

    pip

Ansible installation method:

    pip
    OS package

Actual Behaviour

need to add sysctl parameter so that we can set during runtime.

**Comment by thatsk** [comment]
https://docs.docker.com/engine/reference/commandline/run/#configure-namespaced-kernel-parameters-sysctls-at-runtime

**Comment by thatsk** [comment]
https://docs.docker.com/compose/compose-file/#sysctls

**Comment by thatsk** [comment]
can't we sysctl parameter when container already spin up or when we are spinning up

**Comment by seandst** [comment]
The ansible `docker_container` module's param is `sysctls`, described as a "Dictionary of key,value pairs.": https://docs.ansible.com/ansible/latest/modules/docker_container_module.html

It would be easy enough to add this to the docker create playbook, etc, the difficult part is likely to be updating the schema and related tests to allow the `sysctls` key, and determining what (if any) key/value validation rules to apply.

I think there was a discussion on another issue about how to deal with adding new docker module parameters, but I don't remember where that discussion took place or what conclusions may have been reached in it.

**Comment by thatsk** [comment]
Can't we add in molecule.yaml?

**Comment by thatsk** [comment]
Because when i am trying to change some kernels parameters in running container it's not allowing to do that.

**Comment by thatsk** [comment]
Can you help me ?

**Comment by seandst** [comment]
My apologies, my comment was specifically about changes that would need to be made to molecule to support the use of the `sysctls` parameter in molecule.yml for the docker driver.

The "docker create playbook" that I mentioned is specifically [molecule's embedded create.yml for docker](https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml), but adding a new parameter like this needs a few additional steps. A patch to add support for `sysctls` would probably look a lot like this one, which added `tty` support: https://github.com/ansible/molecule/commit/766dc35b0b0ce498cd5e3a62b40f828742d0d08c.

**Comment by thatsk** [comment]
But what if we need to add multiple parameters like this
sysctls:
  net.core.somaxconn: 1024
  net.ipv4.tcp_syncookies: 0

**Comment by thatsk** [comment]
When we create molecule create it will pick from our molecule yam and configure the container I'm not familiar with source code but happy to help

**Comment by wilmardo** [comment]
@thatsk Provided a PR that implements this option. Feel free to test, the instructions are in the PR #2192
