### ISSUE TITLE
Get Ansible 2.8 CI testing in place

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2049]
Now that https://github.com/ansible/molecule/issues/1727 is in, let's deal with some of those CI TODOs to conver Ansible 2.8 proper:

  * https://github.com/ansible/molecule/blob/master/tox.ini#L42
  * https://github.com/ansible/molecule/blob/master/.travis.yml#L59 (Don't allow failure for 2.8)

And then we can push for a pre-release with more certainty ...

**Comment by znerol** [comment]
A fix for #2053 is needed as well.

**Comment by decentral1se** [comment]
All fixes are out:

  * https://github.com/ansible/molecule/pull/2051
  * https://github.com/ansible/molecule/pull/2050

Reviews welcome!
