### ISSUE TITLE
Installing Molecule

### ISSUE THREAD

**Issue by BElluu** [ansible/molecule#2058]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/belluu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/belluu/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

molecule: command not found

```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:

# Desired Behavior

I installed ansible and after that molecule using pip install and pip3 install. When I check  pip3 list or pip list I see molecule (2.20.1) but when I try use molecule commands, I have "molecule: command not found"

# Actual Behaviour

I tried brew install python but that didn't fix my problem.

**Comment by decentral1se** [comment]
Hi @BElluu, have you used `--user` on the install? Then you might look in `~/.local/bin` and ensure that is on your `$PATH`. OTOH, you seem to have tried a number of conflicting ways of installing the package and I would recommend to try the following:

```
$ mkdir -p molecule-test-folder && cd $_
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -U setuptools pip 'molecule'
$ molecule --version
```

This is Python packaging issue and not something specifically to do with Molecule, so I will close it off for now. Feel free to re-open if you think Molecule is not doing something correctly in this case.

Also, if our installation documentation can be improved, please do feel free to submit a PR against it https://molecule.readthedocs.io/en/stable/installation.html#install.
