### ISSUE TITLE
Deprecation Warning: GCE module will be deprecated in 2.12

### ISSUE THREAD

**Issue by Lirt** [ansible/molecule#2059]
# Issue Type

- Deprecation warning

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.8.0
molecule, version 2.20.1
```

Molecule installation method: `pip`
Ansible installation method: `pip`

# Actual Behaviour

The [GCE module](https://docs.ansible.com/ansible/latest/modules/gce_module.html) will be deprecated in ansible 2.12. 

The [recommendation](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#deprecation-notices) is to use module `gcp_compute_instance`.

This must be reflected in `google` driver cookiecutter template I guess (`https://github.com/ansible/molecule/tree/master/molecule/cookiecutter/scenario/driver/gce`).

Using recommended modules will make playbooks a little more complex, for example you need to also use `gcp_compute_address` to create external address for VM. I am already using this in MongoDB role, where I test 3 node cluster with multiple disks, because it gives me more options.

I can provide some examples if you want. From first glance, there might be needed more variables from user in `platforms` section.

This is not yet big priority, because we still have a lot of time until ansible 2.12.

**Comment by ssbarnea** [comment]
@Lirt the new module was introduced in ansible 2.5 which means that we either need to delay this until we frop support for 2.5, or to comeup with an ugly-trick which used different modules based on ansible version.

I will assign this ticket to you, hoping that you could create PR to address it.

**Comment by ssbarnea** [comment]
Please reopen on https://github.com/pycontribs/molecule-gce

**Comment by MisterMiles** [comment]
If there is no other alternative for the GCE module, the use of Molecule in the Google Cloud is not possible...
