### ISSUE TITLE
Extra vars are not passed to the playbook anymore with converge.

### ISSUE THREAD

**Issue by zeitounator** [ansible/molecule#2061]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.0
  config file = None
  configured module search path = ['/home/olcla/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

molecule (downgraded to 2.20 to fix but problem related to master branch)
```

Molecule installation method (one of):

- pip from git master

Ansible installation method (one of):

- pip

# Desired Behavior

When running `molecule converge -s my_scenario -- -e somevar=value` I expect molecule to pass the extra vars when running playbook.yml

# Actual Behaviour

I was trying to fix deprecations related to ansible 2.8 and had to install molecule from git master to overcome problems with testinfra. When running the above command with the latest molecule master, the extra vars are not passed to the playbook anymore. This is working as expected when downgrading to molecule 2.20.1

**Comment by seandst** [comment]
I broke this in #1739. Sorry about that. I'll get it fixed, and also get it covered by a test so it doesn't happen again. :)
