### ISSUE TITLE
SSHException with latest testinfra

### ISSUE THREAD

**Issue by sassoo** [ansible/molecule#2069]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

`molecule verify` with the vagrant driver using virtualbox should successfully ssh into the guest vm created by molecule. This worked before upgrading to latest molecule & testinfra without changing anything else.

# Actual Behaviour

The error is: `SSHException: No authentication methods available`. If I change the molecule generated ansible inventory files `ansible_private_key_file` key to `ansible_ssh_private_key_file` it works. Additionally, `molecule login` works without issue. This worked before upgrading to latest molecule & testinfra without changing anything else.

Another workaround in a simple test file is:

```
import os

import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')


def test_docker_run(host):
    current = host.backend.ansible_runner.inventory['_meta']['hostvars']['instance-1']['ansible_private_key_file']
    host.backend.ansible_runner.inventory['_meta']['hostvars']['instance-1']['ansible_ssh_private_key_file'] = current
    with host.sudo():
        assert host.run('docker run -t -d --name test alpine cat').rc == 0
        assert host.docker('test').is_running
```

I'm unsure if molecule or testinfra is at fault so posting here first. Let me know if I should post a testinfra issue.

**Comment by decentral1se** [comment]
Thanks for the report! AFAICT, both are still supported in Ansible:

  * https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L147

I did take a look into testinfra and it seems to be making a decision on this:

* https://github.com/philpep/testinfra/blob/master/testinfra/utils/ansible_runner.py#L85

So, it looks like we have a mismatch from testinfra then? We should perhaps try to patch testinfra to support both Ansible advertises that as well. What do you think @sassoo?

**Comment by decentral1se** [comment]
Took a stab in https://github.com/philpep/testinfra/pull/448.

**Comment by sassoo** [comment]
I took a quick glance at the ansible documentation [here](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters) & only saw a reference to ansible_ssh_private_key_file.

Also, many of the other ssh related keys include 'ssh' in the name so for consistency & easy googling I'd probably migrate toward that. If it's a PITA then no big deal but it was the absence of any google results for `ansible_private_key_file` that made me think to test changing it.

**Comment by sassoo** [comment]
Also, thanks for the rapid feedback & testinfra issue! Super cool.

**Comment by decentral1se** [comment]
Cool! Testinfra change is merged now so it's possible to test against latest Testinfra HEAD. I've asked for a release and will close this when that is officially on PyPi. Thanks again for this early testing and feedback.

**Comment by SergeyBear** [comment]
Please reopen #2077 - its not a duplicate
