### ISSUE TITLE
Testinfra 3.0.2 should be installed.

### ISSUE THREAD

**Issue by codequokka** [ansible/molecule#2071]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.0
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/molecule-test/.venv/lib/python3.6/site-packages/ansible
  executable location = /tmp/molecule-test/.venv/bin/ansible
  python version = 3.6.4 (default, May 28 2019, 09:20:39) [GCC 5.4.0 20160609]
molecule, version 2.20.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

None

# Desired Behavior

As stated in setup.cfg, testinfra 3.0.2 should be installed.

# Actual Behaviour
testinfra 1.19.0 is installed.

```zsh
$ mkdir /tmp/molecule-install-test
$ cd /tmp/molecule-install-test
$ pytho3 -m venv .venv
$ source .venv/bin/activate
$ pip install molecule
$ pip list | grep testinfra
testinfra          1.19.0
```

I am newbie about python packaging system, But it seems to me that follwing output is related this issue.
```zsh
$ ag '1\.19\.0' .venv/lib/python3.7/site-packages/molecule-2.20.1.dist-info/METADATA
54:Requires-Dist: testinfra (==1.19.0)
```

**Comment by decentral1se** [comment]
Hi @codequokka, the latest pip installable Molecule does not have the latest testinfra (you can check by taking a look in the latest release files of https://files.pythonhosted.org/packages/8d/51/a691f91a829e0be54c8d898ece232c723936faa408496e8ac87f32846bea/molecule-2.20.1.tar.gz). 

I would recommend installing the latest development pre-release (beware, there are bugs ...) following https://molecule.readthedocs.io/en/latest/installation.html#install or from source (maybe more bugs ...) following https://molecule.readthedocs.io/en/latest/installation.html#source.

Will be closing this off then :+1:
