### ISSUE TITLE
More explicit readme/docs

### ISSUE THREAD

**Issue by trondhindenes** [ansible/molecule#2079]
from the docs: "converge":
"Converge will execute the sequence necessary to converge the instances."

I simply don't understand what that means. I'm trying to figure out the difference between "test", "converge", etc but it's hard. Improved docs would be awesome.

**Comment by fabiencytadel** [comment]
Hi, don't use "Usage" to guide you throught docs.

It's just a remind of what args you can use and a quick description of the purpose. It will be very clear when you know what molecule can do.

Don't rush and take a look at the Getting started Guide, to learn more about scenarios and sequencies.

**Comment by decentral1se** [comment]
Thanks for the feedback @trondhindenes! I'm merging this into https://github.com/ansible/molecule/issues/2264 and will hopefully follow up soon to improve this situation on the documentation.
