### ISSUE TITLE
Make the Dockefile template optional in molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2086]
User experience could be improved if we allow them to use docker testing without having to copy the template Dockerfile from molecule source code.

In many cases they do not have a new to copy that file and they are better off to rely on molecule own copy of it, which would get support for more and more platforms, receive bugfixes. They would not have to face bugs that were already fixed in the template.

**Comment by MarkusTeufelberger** [comment]
See #1642

**Comment by decentral1se** [comment]
This has been done! :fireworks:
