### ISSUE TITLE
Docker driver uses deprecated "docker_image_facts"

### ISSUE THREAD

**Issue by Duckle29** [ansible/molecule#2090]
# Issue Type

- Bug report

# Molecule and Ansible details
| | |
|--|--|
| Ansible  | 2.8.0  |
| Molecule | 2.20.1 |

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:

ansible-lint

# Desired Behavior

No deprecation warnings on creation of a docker instance

# Actual Behaviour

Any molecule create run which invokes the docker driver will warn the user about:

```
[DEPRECATION WARNING]: docker_image_facts is kept for backwards compatibility 
but usage is discouraged. The module documentation details page may explain 
more about this rationale.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg."
```

The problems are at: https://github.com/ansible/molecule/blob/80290902229c0566b7b2c756947366c4df8a8aac/test/resources/playbooks/docker/create.yml#L35
and at: https://github.com/ansible/molecule/blob/80290902229c0566b7b2c756947366c4df8a8aac/molecule/provisioner/ansible/playbooks/docker/create.yml#L34

The fix would be to change those to docker_image_info, the new name for this module as described here: https://docs.ansible.com/ansible/latest/modules/docker_image_facts_module.html

~~I will open a PR doing this~~
This is what is being fixed in: https://github.com/ansible/molecule/pull/2047

**Comment by ssbarnea** [comment]
Fixed in master
