### ISSUE TITLE
Retry action "dependency".

### ISSUE THREAD

**Issue by robertdebock** [ansible/molecule#2114]
# Issue Type

- Feature request

# Desired Behavior

In some cases, I'd guess in 1 &permil; of the cases, molecule fails:

```
--> Action: 'dependency'
    - downloading role 'bootstrap', owned by robertdebock
    - downloading role from https://github.com/robertdebock/ansible-role-bootstrap/archive/3.2.0.tar.gz
 [ERROR]: failed to download the file: The read operation timed out
 [WARNING]: - robertdebock.bootstrap was NOT installed successfully.
```

Now the build fails and a retry typically works.

**Comment by decentral1se** [comment]
We've really suffered from this in our CI, see https://github.com/ansible/molecule/issues/2057. Maybe we could add a simple retry with a back-off of some seconds and a command line flag to enable it. That might save us all some pain of these dodgy network connections. Anyone got a PR for it?

**Comment by decentral1se** [comment]
Anyone against using https://github.com/jd/tenacity or https://github.com/mozilla-releng/redo?

**Comment by seandst** [comment]
Of those, I think tenacity looks a little more flexible (and perhaps more actively maintained) for how we might want to do this, but I have no serious objections to either.
