### ISSUE TITLE
Allow the specification of a custom cookiecutter template for scenario creation

### ISSUE THREAD

**Issue by luyun-aa** [ansible/molecule#2117]
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
```
ansible 2.8.1
molecule, version 2.20.0

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When initiating a test scenario, it would be nice to be able to specify a custom cookiecutter template. To meet internal security requirements we need to make a lot of changes every time we create new roles and scenarios. Now that providing a custom template for role creation is supported, we would love to support the same feature for scenario creation as well.

Proposed way of specifying custom template:
```
molecule init scenario -r role_name -s scenario_name -d docker --driver-template /abs/path/to/cookicutter/template
```

Please note that the template directory consists of directories for one or more customized drivers. For example, if only templates of docker and ec2 driver are customized, the directory structure would look like:
```
> tree /abs/path/to/cookicutter/template
├── docker
│   ├── cookiecutter.json
│   └── {{cookiecutter.molecule_directory}}
│       └── {{cookiecutter.scenario_name}}
│           ├── Dockerfile.j2
│           ├── INSTALL.rst
│           └── playbook.yml
└── ec2
    ├── cookiecutter.json
    └── {{cookiecutter.molecule_directory}}
        └── {{cookiecutter.scenario_name}}
            ├── INSTALL.rst
            ├── create.yml
            ├── destroy.yml
            ├── playbook.yml
            └── prepare.yml
```

When the requested driver is not present in custom template directory, molecule falls back to use default template and gives a warning message.

**Comment by ssbarnea** [comment]
@luyun-aa I support your proposal, my only addition would be that I would like to be able to define an ``MOLECULE_SCENARIO_TEMPLATE=/path/to`` which would allow users to define their default template to be used as this is more convenient than the cli argument which they need to remember to add each time. (cli argument would take precedence).

Good luck making a PR for it! ;)

**Comment by luyun-aa** [comment]
@ssbarnea Thanks for your support. I changed the command line argument to `--driver-template`, and environment variable to `MOLECULE_SCENARIO_DRIVER_TEMPLATE`. The PR is ready for review.
