### ISSUE TITLE
deactivate handler with tag "notest"

### ISSUE THREAD

**Issue by Smuu** [ansible/molecule#2119]
# Issue Type

- Feature request
- Bug report

# Molecule and Ansible details

ansible 2.7.10
molecule, version 2.20.1

Molecule installation method:

- pip

Ansible installation method:

- pip

# Desired Behavior

When using the tag "notest" I can deactivate a task for molecule testing. But adding the "notest" tag to a handler not works as expected. It just run the handler.

**Comment by decentral1se** [comment]
We just use the standard `--skip-tags=SKIP_TAGS` from Ansible so if this isn't working it is an issue with the underyling Ansible implementation and not Molecule. Please see https://groups.google.com/forum/#!topic/ansible-project/qXWpCJ1449E.
