### ISSUE TITLE
proposal: switch readthedocs to single version

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2141]
I would like to propose to reconfigure readtehdocs to keep a single version of molecule docmentation up instead of multiple versions/branches like we have now.

The main reason for this proposal is because Google search is sending users to old versions instead of sending them to latest (master).

If we have a single version this will also improve SEO and people could use permalinks to point to the right section.

Please use up/down thumbs to vote on this.

If we agree on that, one of the admins from RTD could do the switch on https://readthedocs.org/projects/molecule/ -- keep in mind that they state that there is no way to rever to multi-versions once we do it.

**Comment by themr0c** [comment]
Hello, rationale for my -1:

Previously, documentation was pointing out to master only, but it led to trouble when people using the released version of molecule were not finding stuff in the documentation, because documentation was pointing to master, and behavior had changed.

I would think twice before reverting to this old behavior.

**Comment by manics** [comment]
When there's a breaking change in molecule it may not be possible to upgrade immediately so having access to older docs is useful.

RTD have an FAQ for this problem, do you think it would work?
https://docs.readthedocs.io/en/stable/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs

**Comment by decentral1se** [comment]
Alternative to this is to add a custom header to the version saying: "this is old" or "this is the development branch" or whatever. I'm -1 on this.

**Comment by decentral1se** [comment]
This has been around for a while now and there is an majority :-1:, so I'm closing.

Thanks for weighing in folks.
