### ISSUE TITLE
create playbook doesn't pass item.pull to docker_container so pre-build containers are not updated..

### ISSUE THREAD

**Issue by skyscooby** [ansible/molecule#2149]
# Issue Type

- Bug report

# Molecule and Ansible details

Tried setting pull: true in molecule.yml but newer latest image is not actually pullled..
`item.item.pre_build_image = True` for me.. today pull is only used when containers are build locally.

Should the call to this module not pass the pull parameter?
https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L123

As documented here?
https://molecule.readthedocs.io/en/stable/configuration.html#docker

# Desired Behavior

if pull: true is set for the platform.. it should pull the latest image.

# Actual Behaviour

A fresh latest image is not pulled.

**Comment by decentral1se** [comment]
It's being passed https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L85 and https://github.com/ansible/molecule/blob/master/molecule/provisioner/ansible/playbooks/docker/create.yml#L62.

**Comment by skyscooby** [comment]
I am using a pre-build (poorly named, should be pre-built) image, rather than building the test images every single test... we have a hundred ansible roles that all are tested with the same base images, there is no resources or time to build this image every single pipeline. But they do get updated occasionally when we move the stable tag for the image we would like the pipelines to pull the newer version of the test conatiner..  the docker_container module also accepts the pull argument .. and in the case a use has defined both pre_build_image = True and pull = True then I believe it should be passed to the docker_container task.
