### ISSUE TITLE
Add test suite for the Podman driver

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2159]
See https://github.com/ansible/molecule/issues/2158.

And https://github.com/ansible/molecule/issues/2158#issuecomment-509005470.

**Comment by sshnaidm** [comment]
@decentral1se ack, will start looking into it. I'd happy to see any guidelines about molecule tests.

**Comment by decentral1se** [comment]
Bump @sshnaidm, any chance you have time to work on this? RE: guidelines, you can pretty much check the other test suite implementations. It should be self-explanatory. You could just do the unit tests for now and leave the functional tests for when we break this out to a plugin? That should be less work and give us more guarantees here in core for now.

**Comment by sshnaidm** [comment]
@decentral1se sorry for such delay, started to work on this in WIP
