### ISSUE TITLE
Molecule and Ansible Collections

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2165]
See https://github.com/ansible/ansible/pull/57106.

We should try to make it possible to generate and understand collections here in Molecule.

I am not sure how this can be done right now but I'm creating this to track.

If someone has time, please do pick this up. I'll be happy to assist.

**Comment by decentral1se** [comment]
https://github.com/ansible/ansible/pull/57106#issuecomment-500485008?

Unclear what is being planned.

**Comment by jctanner** [comment]
Here's the tentative plan:

* `ansible-galaxy collection` is going to be shipped in ansible-2.9 for all ansible users and customers to use as the standalone way to init, build, publish and install collections without any additional dependencies
* `ansible-test` will be enhanced to understand collections and run sanity/unit/integration tests that we already have in the ansible/ansible repo. It will also become part of the distribution package that ends up in pypi.
* Once the first two items are completed, we can have molecule call out to them directly via the sh library much like molecule does with most other tools.

**Comment by geerlingguy** [comment]
Just posted: [How to add integration tests to an Ansible collection with Molecule](https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule). It seems like only minimal changes were needed (and mostly for CI—for local testing everything pretty much 'just works').

Note that I did not use `molecule init` to generate the Collection (since that's not a thing yet)—but I don't generally use `molecule init` to generate new roles either, I build the role separately, then `molecule init` to add the molecule configuration _to an existing role_, since I have an inherent distrust for 'init' commands of downstream tooling (though it's a silly thing to not trust).

**Comment by decentral1se** [comment]
Thanks for this @geerlingguy, solid stuff.

**Comment by darmach** [comment]
I have some issues using molecule to test the module in a collection. Followed @geerlingguy article, however molecule does not seem to pick up the module for me:
```
--> Action: 'converge'
--> Sanity checks: 'docker'
ERROR! couldn't resolve module/action 'my_test'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/darmach/venvs/mytestrole2/mynamespace/mycollection/molecule/default/playbook.yml': line 16, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
  - name: Test the my_test module.
    ^ here

ERROR:
(mytestrole2 venv)[darmach@mbp] ~/venvs/mytestrole2/mynamespace/mycollection [4] $ tree
.
├── README.md
├── docs
├── galaxy.yml
├── molecule
│   └── default
│       ├── INSTALL.rst
│       ├── molecule.yml
│       ├── playbook.yml
│       └── tests
│           ├── __pycache__
│           │   ├── test_default.cpython-37-pytest-5.2.2.pyc
│           │   └── test_default.cpython-37.pyc
│           └── test_default.py
├── plugins
│   ├── README.md
│   └── modules
│       └── my_test.py
└── roles

8 directories, 10 files
```

Used following ansible and molecule versions:
```
pip install git+https://github.com/ansible/ansible.git@devel
pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple molecule==3.0a4.dev41
```
Are these correct?

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/issues/2380 is the actionable ticket. Closing.
