### ISSUE TITLE
Address psutil dependency challenges 

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2168]
Currently molecule lists pstuil as a dependency just because that is a soft-dependency of the click-complete.

psutil is not a pure-python package and needs to be compiled, making installation process slower and much more likely to fail.

We should investigate different approaches:

* finding a replacement for psutil in our dependency or finding a [replacement for click-completion](https://github.com/click-contrib/click-completion/issues/25)
* moving psutil inside an optional cli extra, as this is clearly not needed for CI usage.
* convincing pstutil maintainers to [publish linux binaries on pypi](https://pypi.org/project/psutil/#files) for it. See https://github.com/giampaolo/psutil/issues/1550

**Comment by decentral1se** [comment]
Option 3 is probably the nicest. I haven't seen an installation issue for this package yet but I know that molecule installation is slow, so this is probably contributing. Let's see what the ticket you raised reveals before trying others?

**Comment by ssbarnea** [comment]
psutil was already removed as a dependency.
