### ISSUE TITLE
Fix flaky "Assert that the envarg envvar was set" on shard 4/4 functional testing

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2177]
The failure is:

```
        TASK [Assert that the envarg envvar was set] ***********************************
        fatal: [instance-e5b7d3b0-d672-44ad-96bc-489571b19fa4]: FAILED! => {
            "assertion": "ansible_env.envarg == 'this_is_a_test'",
            "changed": false,
            "evaluated_to": false,
            "msg": "Assertion failed"
        }
```

https://travis-ci.com/ansible/molecule/jobs/217346483

I can't get this to fail locally. It's something to do with the Travis / Molecule parallelism on the CI.

Any ideas?

@ssbarnea @seandst @themr0c

**Comment by seandst** [comment]
The failing assertion is for `ansible_env.envarg == 'this_is_a_test'`. Looking at the playbook output in `create`, there is a var with that value being set during the Dockerfile creation, `buildargs': {'testarg': 'this_is_a_test'}`. It's not clear to me how that `testarg` value is expected to be stored as `ansible_env.envar` in ansible.

I don't spend a lot of time with the docker driver, so this may be peculiar, or it may be normal. I'm not sure.

**Comment by decentral1se** [comment]
Yeah, my guess is that somehow, the docker image is not being created because it's already been made (idempotence) and then the build arg is not available when the playbook runs. Need to investigate ...
