### ISSUE TITLE
presence of futures==3.1.1 can break molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2181]
I discovered that presence of `futures==3.1.1` would break ansible/molecule. Removal fixed the issue. 

I am not yet sure what installed it so I am unsure how we can prevent it, as it not listed as a dependendecy. Still, it could prove useful to share it.
```
$ molecule create                                                                                                                                                         --> Validating schema /Users/ssbarnea/rdo/rdo-infra/testproject/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── dependency
    ├── create
    └── prepare

--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'create'
Proceed (y/n)? Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/bin/ansible-playbook", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/ssbarnea/os/ansible/bin/ansible-playbook", line 61, in <module>
    import ansible.constants as C
  File "/Users/ssbarnea/os/ansible/lib/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/__init__.py", line 82, in <module>
    _patch_async()
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/__init__.py", line 78, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

Similar to https://github.com/pypa/pipenv/issues/1753

Tracked upstream as https://github.com/agronholm/pythonfutures/issues/90

**Comment by agronholm** [comment]
Triggering this error requires `sys.path` to be manipulated into looking in `site-packages` before the standard library, as well as bypassing all the protections in the `futures` library against being installed on Python 3.

**Comment by agronholm** [comment]
Actually 3.1.1 did not have `python_requires` in place yet, which explains how it was able to get installed on Python 3. Yanking the previous releases or even modifying the code to prevent the `SyntaxError` would not help here though since the dependency is pinned to a specific version.

**Comment by agronholm** [comment]
If you could help track down the culprit library which has this uncalled-for dependency on an old version of `futures`, that would be great. Just seeing the list of installed packages on the affected system would help narrow down the list of suspects.

**Comment by agronholm** [comment]
Come to think of it, even 3.1.1 has the version check in setup.py, so how was it able to get installed? The wheel is a no-go since it's tagged only for Python 2.

**Comment by ssbarnea** [comment]
@agronholm I will do that next time I find it. Now I was only cleaning the bug tracker and I had to reproduce the bug manually. I am curious too.

I found one instance on OpenStack but I doubt it was that one as I never remember to install it. http://codesearch.openstack.org/?q=futures%3D%3D3.1.1&i=nope&files=&repos= -- sadly github search seems to fail to search on exact matches.

Now the reality is that pip will pick 3.1.1 if anyone just adds `futures` as a generic requirement, because that is the latest version that is compatible with python3 from the metadata point of view. This would explain why we keep seeing people installing it.

Try to hide all versions with broken metadata from pypi, this is not a destructive measure but will likely prevent users from adding dependencies incorrectly.

**Comment by agronholm** [comment]
I just tried installing `futures` on Python 3 and, to my surprise, it worked. I'm still not sure how, as the wheel build has to go through `setup.py` and that file triggers a fatal error.

**Comment by agronholm** [comment]
I would add that even when the install was successful, I could not trigger the `SyntaxError` since the standard library takes precedence in the import.

**Comment by agronholm** [comment]
> Try to hide all versions with broken metadata from pypi, this is not a destructive measure but will likely prevent users from adding dependencies incorrectly. What will happen is that pip will (likely, based on version) report a failure to install any futures compatible with your python.

No, the process IS destructive. Those releases can never be reuploaded and this risks hurting legitimate users.

**Comment by ssbarnea** [comment]
@agronholm Yep, i forgot that the hide option was dropped from the newer wheelhouse. This means that you have only one option: make a newer release that is fixing the invalid syntax problem but which does not have python requires (mainly the 3.1.1post0), so those putting wrong dependencies will not break other tools.

Other attempts to fix this would involve re-releasing all previous releases and that is an insane effort that would clearly upset users too.

In fact you could do another dirty trick: you could make a fake release that is empty and that requires python3. So those using it incorrectly will get... nothing, avoiding a breakage. This will sort out the issue where doing `pip3 install futures` does break you environment.

**Comment by agronholm** [comment]
> Other attempts to fix this would involve re-releasing all previous releases and that is an insane effort that would clearly upset users too.

Actually this is impossible, for the reason mentioned above.

> In fact you could do another dirty trick: you could make a fake release that is empty and that requires python3. So those using it incorrectly will get... nothing, avoiding a breakage. This will sort out the issue where doing pip3 install futures does break you environment.

This sounds unorthodox, but brilliant. Since getting rid of the problematic releases might break things for existing users, this seems like it could really fix the problem once and for all, provided of course that users don't pin to older releases.

**Comment by agronholm** [comment]
I misread the setup.py code earlier and mistook the warning for an exception. That is why the install still works. Adding a dummy py3 wheel for 3.1.1 sounds like the best option here.

**Comment by agronholm** [comment]
I have now uploaded a dummy py3 wheel for 3.1.1. Let's hope this avoids some of the grief caused by bad packaging.

**Comment by ssbarnea** [comment]
Fixed in two ways. Thanks @agronholm
