### ISSUE TITLE
Specify ansible binary location

### ISSUE THREAD

**Issue by javierjimsa** [ansible/molecule#2185]
# Issue Type

- Feature request

# Molecule and Ansible details

ansible --version && molecule --version
molecule 2.19.0
ansible 2.7.6

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip custom location

# Desired Behavior

Being able to select where the ansible binary is located, since in our installation molecule and ansible are not installed in the pip default location, then when molecule is executed it uses the ansible system version not the one installed in the custom location .

Is there a possibility to change where molecule looks for ansible?

Thanks in advance!

**Comment by ssbarnea** [comment]
This won't happen because it is up to the user to decide how he wants to install it. Everywhere where I use molecule, I use it from inside tox with isolated virtualenvs, so it would never use system ansible.
