### ISSUE TITLE
platforms / env: AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"

### ISSUE THREAD

**Issue by src386** [ansible/molecule#2186]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xavier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xavier/.local/lib/python3.7/site-packages/ansible
  executable location = /home/xavier/.local/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
molecule, version 2.20.2
```

Molecule installation method (one of):

- pip3

Ansible installation method (one of):

- pip3

# Desired Behavior

molecule.yml:
```
platforms:
  - name: instance
    image: centos:7
    env:
      foo: bar
```

I expect foo=bar to be passed during Docker build. Used to work for a long time.

# Actual Behaviour

`env` seems to not work at all, whatever the variable type and value. Always crashes:

```
TASK [Create Dockerfiles from image names] *************************************
    task path: /home/xavier/.local/lib/python3.7/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml:21
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: xavier
    <127.0.0.1> EXEC /bin/sh -c 'echo ~xavier && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/xavier/.ansible/tmp/ansible-tmp-1564143768.866613-11304981205851 `" && echo ansible-tmp-1564143768.866613-11304981205851="` echo /home/xavier/.ansible/tmp/ansible-tmp-1564143768.866613-11304981205851 `" ) && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/xavier/.ansible/tmp/ansible-tmp-1564143768.866613-11304981205851/ > /dev/null 2>&1 && sleep 0'
    failed: [localhost] (item={'name': 'instance', 'image': 'centos:7', 'env': {'foo': 'bar'}}) => {
        "ansible_loop_var": "item",
        "changed": false,
        "item": {
            "env": {
                "foo": "bar"
            },
            "image": "centos:7",
            "name": "instance"
        },
        "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"
    }
```

**Comment by src386** [comment]
Apparently the problem does not occur using Python2:

```
ansible 2.8.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xavier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xavier/.local/lib/python2.7/site-packages/ansible
  executable location = /home/xavier/.local/bin/ansible
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
molecule, version 2.20.2
```

**Comment by ssbarnea** [comment]
There is no `iteritems` in molecule codebase.

**Comment by src386** [comment]
@ssbarnea can you please be more specific before closing the issue? 
I don't even know what you are talking about.
Do you mean it's related to Ansible ? 

I'm not doing black magic, it's present in the molecule documentation: https://molecule.readthedocs.io/en/stable/configuration.html#provisioner

```
provisioner:
  name: ansible
  env:
    FOO: bar
```

And this is obviously not working.

My goal is to inject http_proxy environment settings.

**Comment by src386** [comment]
Nevermind, just found the `iteritems` in the custom Dockerfile.j2 I'm using.
Seems like it's not working with python3, I will investigate.

**Comment by seandst** [comment]
`iteritems` is a python2-only dict method. It is very rare that `iteritems` is needed instead of just `items`, which exists in both python2 and python3 with basically the same interface (`for key, value in dict_object.items(): ...`).

**Comment by src386** [comment]
This is what I did, I was not aware of the `iteritems` in the Dockerfile but after replacing with `items` it works. Good thing if it's python2 and python3 compatible, thank you @seandst
