### ISSUE TITLE
"ansible_connection" variable is read as "smart" when executing verify with testinfra over delegated driver

### ISSUE THREAD

**Issue by javierjimsa** [ansible/molecule#2199]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.6
molecule 2.20.2
python 3.7.3

Molecule installation method (one of):

- pip with virtual env

Ansible installation method (one of):

- pip with virtual env


```
source .venv/bin/activate
pip3 install ansible==2.7.6 molecule docker dnspython pytest-json pytest-xdist
```

Detail any linters or test runners used:

used the default by molecule

# Desired Behavior
when executing molecule test, at verify step test are executed.

# Actual Behaviour

instead ansible connection is read as smart at this step but previous steps as converge or prepare are executed correctly.

```
--> Scenario: 'vmware'
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [molecule_generated_175]
    
    TASK [role_execution_dir : Install httpd] **************************************
    changed: [molecule_generated_175]
    
    PLAY RECAP *********************************************************************
    molecule_generated_175     : ok=2    changed=1    unreachable=0    failed=0
    
    
--> Scenario: 'vmware'
--> Action: 'idempotence'
Idempotence completed successfully.
--> Scenario: 'vmware'
--> Action: 'side_effect'
Skipping, side effect playbook not configured.
--> Scenario: 'vmware'
--> Action: 'verify'
--> Executing Testinfra tests found in /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/molecule/vmware/../../tests/...
    ============================= test session starts ==============================
    platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/.venv/bin/python3
    rootdir: /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir
    plugins: forked-1.0.2, json-0.4.0, xdist-1.29.0, testinfra-3.0.6
    
gw0 I
[gw0] linux Python 3.7.3 cwd: /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/molecule/vmware
    
gw0 C
[gw0] Python 3.7.3 (default, Jul 25 2019, 17:29:06)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
    
gw0 ok
gw0 [2]
    scheduling tests via LoadScheduling
    
    ../../tests/test_httpd.py::test_passwd_file[ansible:/molecule_generated_175]
    [gw0] [ 50%] FAILED ../../tests/test_httpd.py::test_passwd_file[ansible:/molecule_generated_175]
    ../../tests/test_httpd.py::test_httpd_is_installed[ansible:/molecule_generated_175]
    [gw0] [100%] FAILED ../../tests/test_httpd.py::test_httpd_is_installed[ansible:/molecule_generated_175]
    
    =================================== FAILURES ===================================
    ______________ test_passwd_file[ansible://molecule_generated_175] ______________
    [gw0] linux -- Python 3.7.3 /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/.venv/bin/python3
    
    host = <testinfra.host.Host object at 0x7fbf95df4908>
    
        def test_passwd_file(host):
    >       passwd = host.file("/etc/passwd")
    
    ../../tests/test_httpd.py:12:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:107: in __getattr__
        obj = module_class.get_module(self)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/base.py:22: in get_module
        klass = cls.get_module_class(_host)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/file.py:187: in get_module_class
        if host.system_info.type == "linux":
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:143: in type
        return self.sysinfo["type"]
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/__init__.py:44: in __get__
        value = obj.__dict__[self.func.__name__] = self.func(obj)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:33: in sysinfo
        uname = self.run_expect([0, 1], 'uname -s')
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:71: in run
        return self.backend.run(command, *args, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/backend/ansible.py:46: in run
        ssh_identity_file=self.ssh_identity_file)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:181: in run
        return self.get_host(host, **kwargs).run(command)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:177: in get_host
        self.ansible_config, self.inventory, host, **kwargs)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    config = <configparser.ConfigParser object at 0x7fbf95e584a8>
    inventory = {'_meta': {'hostvars': {'molecule_generated_175': {'ansible_connection': 'smart', 'ansible_host': '10.120.52.24', 'ans...on_dir/vmware/ssh_key', ...}}}, 'all': {'children': ['ungrouped']}, 'ungrouped': {'hosts': ['molecule_generated_175']}}
    host = 'molecule_generated_175', ssh_config = None, ssh_identity_file = None
    
        def get_ansible_host(config, inventory, host, ssh_config=None,
                             ssh_identity_file=None):
            if is_empty_inventory(inventory):
                return testinfra.get_host('local://')
            hostvars = inventory['_meta'].get('hostvars', {}).get(host, {})
            connection = hostvars.get('ansible_connection', 'ssh')
            if connection not in ('ssh', 'local', 'docker', 'lxc', 'lxd'):
                raise NotImplementedError(
    >               'unhandled ansible_connection {}'.format(connection))
    E           NotImplementedError: unhandled ansible_connection smart
    
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:71: NotImplementedError
    __________ test_httpd_is_installed[ansible://molecule_generated_175] ___________
    [gw0] linux -- Python 3.7.3 /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/.venv/bin/python3
    
    host = <testinfra.host.Host object at 0x7fbf95df4908>
    
        def test_httpd_is_installed(host):
    >       httpd = host.package("httpd")
    
    ../../tests/test_httpd.py:18:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:107: in __getattr__
        obj = module_class.get_module(self)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/base.py:22: in get_module
        klass = cls.get_module_class(_host)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/package.py:69: in get_module_class
        if host.system_info.type == 'windows':
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:143: in type
        return self.sysinfo["type"]
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/__init__.py:44: in __get__
        value = obj.__dict__[self.func.__name__] = self.func(obj)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:33: in sysinfo
        uname = self.run_expect([0, 1], 'uname -s')
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:71: in run
        return self.backend.run(command, *args, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/backend/ansible.py:46: in run
        ssh_identity_file=self.ssh_identity_file)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:181: in run
        return self.get_host(host, **kwargs).run(command)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:177: in get_host
        self.ansible_config, self.inventory, host, **kwargs)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    config = <configparser.ConfigParser object at 0x7fbf95e584a8>
    inventory = {'_meta': {'hostvars': {'molecule_generated_175': {'ansible_connection': 'smart', 'ansible_host': '10.120.52.24', 'ans...on_dir/vmware/ssh_key', ...}}}, 'all': {'children': ['ungrouped']}, 'ungrouped': {'hosts': ['molecule_generated_175']}}
    host = 'molecule_generated_175', ssh_config = None, ssh_identity_file = None
    
        def get_ansible_host(config, inventory, host, ssh_config=None,
                             ssh_identity_file=None):
            if is_empty_inventory(inventory):
                return testinfra.get_host('local://')
            hostvars = inventory['_meta'].get('hostvars', {}).get(host, {})
            connection = hostvars.get('ansible_connection', 'ssh')
            if connection not in ('ssh', 'local', 'docker', 'lxc', 'lxd'):
                raise NotImplementedError(
    >               'unhandled ansible_connection {}'.format(connection))
    E           NotImplementedError: unhandled ansible_connection smart
    
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:71: NotImplementedError
    - generated xml file: /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/tests/reports/junit.xml -
    - generated json report: /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/role_execution_dir/tests/reports/report.json -
    =========================== 2 failed in 1.38 seconds ===========================
An error occurred during the test sequence action: 'verify'. Cleaning up.
```

**Comment by ssbarnea** [comment]
Yes, default is smart, the same as the ansible default. See https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html -- you can also find it in the source if you search for smart.

**Comment by javierjimsa** [comment]
> Yes, default is smart, the same as the ansible default. See https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html -- you can also find it in the source if you search for smart.

So, do you have some hints about why this is not working?
