### ISSUE TITLE
Document compatibility with Python and Ansible ?

### ISSUE THREAD

**Issue by src386** [ansible/molecule#2212]
I am using molecule in gitlab-ci and it fails because a warning is interpreted as a job error.

This happens during the ```ASK [Wait for instance(s) deletion to complete]``` step when using python 3.7 + ansible 2.8.3 + molecule 2.20.2:

```
"stderr": "/root/.ansible/tmp/ansible-tmp-1565252767.211244-274908763512157/AnsiballZ_docker_container.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\n",
```

This warning does not happen when using python 3.6 + ansible 2.8.3 + molecule 2.20.2 so this is just what I will do.

The question/request is: Is there a documentation about molecule compatibility with python and ansible ? Some kind of table indicating which version of python and ansible I should use with molecule.

**Comment by decentral1se** [comment]
That's probably related to https://github.com/ansible/ansible/issues/55213.

We support whatever Ansible supports, AFAIK. Does Ansible have a documentation page on this? We should link to that. Otherwise, I would be OK with adding a "we support what ansible supports" clause to the documentation.
