### ISSUE TITLE
quay.io/ansible/molecule DIND container is missing some crucial packages

### ISSUE THREAD

**Issue by jamesla** [ansible/molecule#2227]
# Issue Type

- Bug report

The DIND docker image quay.io/ansible/molecule container is missing some crucial packages which are required for pretty much core functionality of molecule.

1. Git  - required for ansible-galaxy to install private ansible roles
2. Rubocop - a linter used by molecule is broken
3. inspec - one of the test frameworks used by molecule
4. ansible 2.8 - only 2.7 is installed and 2.8 brought out a bunch of new modules

This dockerfile used to be kept inside this project back in the retr0h days but I think it's gone now. I am happy to send a PR but where is the dockerfile hosted now?

**Comment by ssbarnea** [comment]
AFAIK, the docker container used by quay.io is the Dockerfile from the root of molecule project and quay is building it itself when a tag is pushed. That made me discover https://github.com/ansible/molecule/issues/2225 which I still have no clue on how to address.

Don't forget to join irc channel, maybe we can fix few things today.

**Comment by jamesla** [comment]
@ssbarnea ok so after a bit more investigation it looks like most of the dockerfile is ok with the exception of Ruby which was broken and have opened a PR here https://github.com/ansible/molecule/pull/2238

However not too sure about the quay.io docker repository and how that works. So I've pushed a temp version to jamesla/molecule in the meantime if anyone else is having problems here.

**Comment by jamesla** [comment]
Ok after a bit more looking around it looks like the build system may be working as there is a build from 3 days ago however it's just never tagging the newest image with the tag latest and pushing that also. This means that if you don't hardcode a tag you get a very old version with the symptoms I posted above.

Who looks after this build system and where is it configured?

**Comment by decentral1se** [comment]
What's the status on this? I see https://github.com/ansible/molecule/pull/2238 was closed but was solving something? Is https://github.com/ansible/molecule/pull/2238#issuecomment-524338726 useful? To answer the build question, we can arrange to contact the admins of this quay setup for a fix but we need to have some idea of the problem first.

**Comment by jamesla** [comment]
There was another PR that went in and fixed the issues. The only remaining issue is that the image tagged as master isn't being pushed (meaning you have to specify the version when pulling the image). Other than that this is all working for me now.
