### ISSUE TITLE
proposal: update list of cores

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2235]
As current I ended up being the only active core on molecule this prevents me from making any changes myself. 

Lets add the following people as cores, so their reviews would be count. All of them are OpenStack contributors where we have a well established review practices (usual requirement being to have at least two others reviewers instead of one). 
```
github username (irc nick if different)
@cloudnull
@ekultails
@gabrielecerami (panda)
```

As a note to others interested in contributing: you can easily become a core on molecule even if you do not create patches yourself, is more important to be willing to do good quality reviews so please review existing PRs even if you are not a core (your review will have a grey mark instead of colored one but it is valuable too).

**Comment by ssbarnea** [comment]
Thanks, done. We will reopen if further updates are needed.

**Comment by gundalow** [comment]
Just to clarify, the above three people have commit powers, thanks :)
