### ISSUE TITLE
Github Action Example

### ISSUE THREAD

**Issue by sblack4** [ansible/molecule#2246]
# Issue Type
- Feature request
DOCS
# Desired Behavior
I'm using molecule with [Github Actions](https://github.com/features/actions). I've got a working example in [a repo I created for a quick demo](https://github.com/rhythmictech/ansible-role-molecule-demo). Could I add an example to the [testing section in the docs](https://molecule.readthedocs.io/en/stable/testing.html?highlight=roles#continuous-integration)? 

Thank you 😄

**Comment by ssbarnea** [comment]
Obviously that you can made a PR and for a simple documentation improvement you can even bypass the step of creating a bug for it. Just create a PR, if is clean and simple it will merge quickly.

**Comment by gundalow** [comment]
Live at https://molecule.readthedocs.io/en/latest/ci.html
