### ISSUE TITLE
support: pre built container wont stay up

### ISSUE THREAD

**Issue by drewmullen** [ansible/molecule#2251]
I posted in IRC and also in r/ansible - I cannot seem to figure this out... hoping for some help

I have a container that works great when i run it locally but does not function inside molecule. hoping for some help to figure out whats up

```
$ docker pull drewmullen/docker-vault-ent:1.2.2
$ docker run -it -p 8200:8200 -e 'VAULT_DEV_ROOT_TOKEN_ID=root' <image id>
```

working:
```
$ curl http://127.0.0.1:8200/v1/sys/health
{"initialized":true,"sealed":false,"standby":false,"performance_standby":false,"replication_performance_mode":"disabled","replication_dr_mode":"disabled","server_time_utc":1566910105,"version":"1.2.2+ent","cluster_name":"vault-cluster-e47cf8a3","cluster_id":"00d81026-cb98-afab-90bb-e7e0c0c10115"}
```
but when i run it with Molecule the service shuts down immediately:

```
$ cat molecule.yml
...
platforms:
  - name: instance
    image: drewmullen/docker-vault-ent:latest
    pre_build_image: true
    exposed_ports:
      - 8200/tcp
    publish_ports:
      - 0.0.0.0:8200:8200/tcp
    env:
      VAULT_DEV_ROOT_TOKEN_ID: root
...
```

error on login:
```
$ molecule login
--> Validating schema /Users/dmullen/git/molecule/namespaces/molecule/default/molecule.yml.
Validation completed successfully.
Error response from daemon: Container 10c74c70b67949497fa1de0c3e36a89957b12723d0a27c327c52d81e699cb00d is not running
```

Heres the dockerfile used to build the registry image with `--build-arg ENTERPRISE_TRIAL=true`

https://github.com/drewmullen/docker-vault/blob/master/0.X/Dockerfile

**Comment by ssbarnea** [comment]
If you look at Dockerfiles you will see that they all have an endless loop. That is what keeps them running. If you use a pre-build image which does not have an endless loop, it will quickly exit.

Probably you can easily solve the problem by adding `command: sleep infinity` parameter, which is documented at https://molecule.readthedocs.io/en/stable/configuration.html

**Comment by drewmullen** [comment]
thanks @ssbarnea im glad you brought that up. I was playing with that config option a few days ago. I wasn't able to connect even after using that but as i was playing with it again today, to share outputs to this ticket, i noticed something that could be significant. Take notice of the `ports` section below

added to molecule.yml
```
    command: server -dev && sleep 10000
    override_command: true
```

```
$ docker container list --no-trunc
CONTAINER ID          IMAGE                     COMMAND                                             CREATED              STATUS              PORTS                    NAMES
<redacted>   a9be82e50c70                         "docker-entrypoint.sh server -dev"                  42 seconds ago       Up 41 seconds       0.0.0.0:8205->8200/tcp   lucid_fermi
<redacted>   drewmullen/docker-vault-ent:latest   "docker-entrypoint.sh server -dev && sleep 10000"   About a minute ago   Up About a minute   8200/tcp                 instance
```
the 1st line item is running native docker using the command i sent in OP, which works. 2nd line is the container deployed by molecule, which does not work.

**Question:** have i mapped the `exposed_ports` and `publish_ports` parameter correctly to molecule.yml?

molecule.yml
```
    exposed_ports:
      - 8200/tcp
    publish_ports:
      - 0.0.0.0:8200:8200/tcp
```

docker
`docker run -it -p 8205:8200 -e 'VAULT_DEV_ROOT_TOKEN_ID=root' a9be82e50c70`

**Comment by drewmullen** [comment]
the issue was that i was using `publish_ports` and the parameter is `published_ports`
