### ISSUE TITLE
determine class and api function naming terminology

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2278]
As we are going towards making molecule plugin based and adding an API to it, we need to be far more careful about how molecule code is used. During the previous months I faces few issues and I think it would worth making some decisions now before we hit first api/plugin enabled version 3.0, so we document the entry points and avoid breaking consumers on new releases.

## Driver class

Currently the base class for drivers is named `Base`... and users have to import it using `from molecule.driver.base import Base`. I find both class name confusing and the way to import too specific on its implementation. 

I would prefer something like:
```
from molecule import Driver
# or MoleculeDriver -- not sure if Molecule prefix would be better or not
```

## Getting drivers
Current implementation requires `from molecule.api import molecule_drivers`. 

I kinda find the molecule_ prefix being redundant here and I can see how in the future, when we will add more and more functions, we will have to type more and more boilerplate.

How about this:
```
from molecule.api import drivers
from molecule.api import verifiers
from molecule.api import linters
```

**Please add your suggestions** here as now is the time when we can still make changes like this as we do not officially have any contracts (pytest-molecule is the only one that could be affected but I can take care of that, but very soon we will have driver plugins).

**Comment by decentral1se** [comment]
Happy with your proposals and agree across the board with suggestions.

**Comment by ssbarnea** [comment]
Closing it now as most obviously parts were fixed, obviously that if can find others we can fix them and point to this issue.
