### ISSUE TITLE
role template should not use "role:" block

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2279]
Role template should not use "role:" block because is harder to maintain than the newer task `include_role`.

Note: patches welcomed, this should be a easy to implement first time contribution.

Use UP/DOWN thumbs to vote for this change.

**Comment by decentral1se** [comment]
I've made a new label for that, good idea to make this clear. Perhaps we can also advertise this on the README or somewhere useful for people who want to get started with helping.

**Comment by mjlshen** [comment]
I'd be happy to help submit a pull request - I'm pretty new here, but I've been using molecule for a while. To be clear, we would like to update the 'role:' blocks in the cookiecutter roles?

**Comment by decentral1se** [comment]
Hey, cool @mjlshen! Sounds like it. If you want, just take a shot at the PR and we'll give it a review for sure. More hands on deck around here would be pretty nice.
