### ISSUE TITLE
Unable create instance using "molecule create"

### ISSUE THREAD

**Issue by Jyonanda** [ansible/molecule#2302]
Hi,
 I am trying to create instance but getting below error.
TASK [Create Dockerfiles from image names] *************************************
    task path: /usr/local/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/create.yml:25
    fatal: [localhost]: FAILED! => {
        "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"
    }

    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

ERROR:

Can someone please help on this?

Thanks.

**Comment by ssbarnea** [comment]
As mentioned in template, please use StackOverflow for questions. `export MOLECULE_NO_LOG=0`
