### ISSUE TITLE
plugins: externalize vagrant driver

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2315]
Like other drivers we should look to move it out of core ASAP, especially as it poses several issues:

* not tested
* on linux vagrant is incompatible with libvirt
* [vagrant is not published in a yum repository](https://github.com/hashicorp/vagrant/issues/11070), only as a rpm which makes impossible to automate installation of latest version or to upgrade it using the system components

**Comment by apatard** [comment]
While I understand the need to remove less tested modules, please note that:

- vagrant is compatible with libvirt, thanks to the vagrant-libvirt project
- the vagrant driver works at least for me on molecule 2.X (and I'm using libvirt VM spawned by vagrant)
- the world is not limited to YUM. For instance, vagrant and vagrant-libvirt are in Debian repositories.

As regards the commit, please note that:
- from a quick look, I don't see any documentation about how to migrate / install the driver
- it's not possible to install it with pip (possibly related to the lack of documentation ?):
```
$ pip install --user molecule-vagrant
...
HTTPError: 404 Client Error: Not Found for url
$ pip3 install --user molecule-vagrant
...
HTTPError: 404 Client Error: Not Found for url
```
So, how to use vagrant with molecule 3.0 ?
I guess I'm going to stick with 2.X for now
