### ISSUE TITLE
How to run prepare playbook on one server but playbook on another?

### ISSUE THREAD

**Issue by kozicpetar** [ansible/molecule#2340]
Hi at all,
I have one question, I will try to describe to you my problem, please check and tell me is that possible to do.

I'm using molecule and DroneCI for automatic testing my playbooks. Because molecule doesn't have support for Proxmox natively, but Ansible has Proxmox module, I wrote prepare playbook which creates LXC container on Proxmox server. That works well, but problem is that because my LXC container get IP from DHCP server and I don't have a solution to run my playbook on that newly created LXC because I don't have that IP in my inventory.

Does exists some solution for this problem or does anyone have some idea how can I do this? 

Thank you.

**Comment by decentral1se** [comment]
> https://github.com/ansible/molecule/blob/master/.github/ISSUE_TEMPLATE/question.md
