### ISSUE TITLE
Are you planning to develop proxmox driver in the future?

### ISSUE THREAD

**Issue by kozicpetar** [ansible/molecule#2359]
Hi at all,
please tell me do you plan to involve Proxmox driver in the future.
In general Proxmox as open-source hypervisor, it is quite widespread. I suppose you know that on Proxmox you can to use KVM virtual machines and LXC containers?

That will be fine feature if you can involve that and support.
I can get you some help in testing and with information about Proxmox API if you need it.
Thank you.

**Comment by mihai-satmarean** [comment]
proxmox plugin is something we are willing to test and help with too!

**Comment by mihai-satmarean** [comment]
> Yes as a plugin, not in core. As of today the master code already supports external plugins and we already moved azure one outside, planning to move of of the others too before we finally release 3.0.
> 
> Writing plugins is currently not really documented but you are more than welcomed to look at https://travis-ci.com/pycontribs/molecule-azure and to ask us on irc if you need more info to write a new driver.

btw, the link is not working from my side

**Comment by ssbarnea** [comment]
I updated the link, I recommend inspiring from existing drivers that are included in the toolset, see https://github.com/ansible-community/toolset/blob/main/requirements.in -- usually we include only actively maintained driver in the toolset.

To write the a new driver fork existing one that in theory appears to be more similar in nature, and modify it, change its name and its playbooks. It is far easier than one would imagine as you will endup only updating few playbooks.

Avoid forking containers driver, that one is a special case: is only a "router" towards podman or docker, not a real driver.

**Comment by ssbarnea** [comment]
@mihai-satmarean I seen that you logged out from irc. To not loose history either setup your own BNC solution, use https://www.irccloud.com/pricing or I can create you an account on my own https://irc.sbarnea.com/

**Comment by mihai-satmarean** [comment]
> @mihai-satmarean I seen that you logged out from irc. To not loose history either setup your own BNC solution, use https://www.irccloud.com/pricing or I can create you an account on my own https://irc.sbarnea.com/

yes please
