### ISSUE TITLE
Dependencies caught in the linter

### ISSUE THREAD

**Issue by evitalis** [ansible/molecule#2426]
# Issue Type

- Bug report

# Molecule and Ansible details

```
Ansible: 2.8.1 & 2.8.4
Molecule: 2.22 & latest git checkout of master branch
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- source
- pip

Detail any linters or test runners used:

Standard linter set, flake8, ansible-lint, yamllint

# Desired Behavior

Only the specified role should be linted and not the dependency. Since each role should be standalone and in its own repository this doesn't make as much sense. Even in a monolithic repository roles are tested individually by molecule. Generally the failure happens during the ansible-lint step.

In this case I did fix the dependent roles but the changes were not yet ready for production use and were done separately to the offending role.

# Actual Behavior

This was tested on the current stable and RC releases as well as currently supported ansible versions.

Molecule fails the linting step because dependent roles are linted. This may be similar to #1908 which should have been fixed by #2215. With that in mind I did grab the newest release to test with and saw the same issue. I did see the sequence was reordered as expected which made this more odd.

Not in front of a system where I can get a full debug output at the moment, but am happy to update this later if needed with said information.

I am curious if this could be since I define the dependency in meta/main.yml which is automatically created, including said key, by ansible-galaxy when initializing a new role. Additionally, said metadata file also fails linting out of the box but that is an issue for the ansible repo itself I think.

**Comment by ssbarnea** [comment]
I am not sure if this is a bug or only needs documentation. I encountered it myself and the workaround was to add relative excludes in `.ansiblelint` config. 

This is due to how linting works (and loads dependencies) so I will close it because is not molecule job to decide how the linting should work.
