### ISSUE TITLE
Update documents according to the molecule-plugins move

### ISSUE THREAD

**Issue by apatard** [ansible/molecule#3834]
I was thinking about creating a bug report template for molecule-plugins and noticed that the molecule ``.github/ISSUE_TEMPLATE/config.yml`` was still pointing to old repositories for the plugins moved to molecule-plugins. This file and (at least) documentation files should probably be checked to ensure they've been updated for that.

**Comment by Qalthos** [comment]
This issue seems to have been solved as of https://github.com/ansible/molecule/pull/4035, please open a new issue if you still have problems, thanks.
