### ISSUE TITLE
Github organization move

### ISSUE THREAD

**Issue by cidrblock** [ansible/molecule#3988]
With the move to the ansible orgnaization in Github, the repo permissions needed to be reset.

Please reach out if you have any issues related to this.

thanks- 

Brad (cidrblock)

**Comment by zhan9san** [comment]
@cidrblock 

Could I still have permission to merge PR/close issue?

**Comment by zhan9san** [comment]
It works. Thx, @cidrblock

**Comment by cidrblock** [comment]
done
