### ISSUE TITLE
Incorrect pip install documentation

### ISSUE THREAD

**Issue by anshulbehl** [ansible/molecule#4043]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [x] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

This is a documentation bug on the pip install of molecule

### What happened

https://ansible.readthedocs.io/projects/molecule/installation/#pip

The above docs mention ansible-core as not a direct dependency, but looks like it is if I do a pip instal or I check 

https://github.com/ansible/molecule/blob/v6.0.2/.config/requirements.in#L2

**Comment by alisonlhart** [comment]
Fixed in #4279.
