### ISSUE TITLE
Update documentation about default Driver

### ISSUE THREAD

**Issue by marcinpraczko** [ansible/molecule#4088]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

-  `molecule --version`
```
molecule 6.0.2 using python 3.11 
    ansible:2.15.6
    default:6.0.2 from molecule
```

- system info
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
```

### What happened

I was working with `molecule` few years back and now I needed to work with it one more time. I was surprised that a lot old working drivers (for example `vagrant`) has been removed. And there is default driver which there is little information about. Even displaying following command not giving any hints:

```
molecule drivers

# Result
default
```

There is no extra information what `default` means and there is little information on documentation. Once I found 'somewhere' that this is default `ansible` driver. However not too much information what this means. 

I was really surprised to see that running command `molecule test` is really running `ansible` on my machine (not sandbox, not VM, not docker) - directly running on my machine. I was lucky that I was working on very simple role for testing - and nothing broke, however I don't think that is right behavior. 

For example working on role which installing new version of software - will cause that this software will be installed on local machine. This is not always recommended way - for example contribution for open source role is dangerous now, because default driver is running on local developer machine.

I was not able find any documentation / information to explain this before run.

**What I would expect**
- Clear information about driver when running command `molecule drivers` - Maybe some command `molecule drivers info default`? Where there will be CLEAR information what will happen.
- Easy to find documentation about default driver - also with CLEAR information how this is working

### Reproducing example

```yml
- Create simple role with default driver for molecule: `molecule init scenario new-role`
- Run `molecule test` --- with Default driver - this is running on local machine ????!

So if role is having any command such as `install package / apt / yum / etc` - this will run on local machine not any sandbox / container / VM.
```

**Comment by ssbarnea** [comment]
@marcinpraczko There is a pending change that will make the driver listing more informative.

Your remark regarding security is bit misleading because running any software locally is unsafe  and it was already possible for anyone to put some playbooks that do nasty stuff regardless which driver was the default. Basically this behavior is not less secure than before.

We would welcome any PRs that also improve the docs.
