### ISSUE TITLE
molecule init scenario -d <anydriver> fails with invalid value

### ISSUE THREAD

**Issue by khurley** [ansible/molecule#4327]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

$ molecule --version
molecule 6.0.3 using python 3.9 
    ansible:2.15.13
    default:6.0.3 from molecule

### What happened

I am trying to specify a driver name of 'podman' or 'vagrant' and molecule rejects the name for the driver.

$ molecule init scenario -d podman oscontainers
Usage: molecule init scenario [OPTIONS] [SCENARIO_NAME]
Try 'molecule init scenario --help' for help.

Error: Invalid value for '--driver-name' / '-d': 'podman' is not 'default'.

### Reproducing example

```yml
This is failing at the command line - there is no example
```

**Comment by Qalthos** [comment]
Molecule 6.0.3 is now just under [a year old](https://github.com/ansible/molecule/releases/tag/v6.0.3), and we no longer support Molecule on Python 3.9.

That said, this looks like the error message I would expect when [molecule-plugins](https://github.com/ansible-community/molecule-plugins) is not installed, as the only driver shipped with Molecule is the delegated driver
